datacatalogue.comment="Данные для микросервиса DATACATALOGUE"
datacatalogue.host_and_port.comment="GRPC host and port"
datacatalogue.host_and_port.DATACATALOGUE_GRPC_HOST="localhost"
datacatalogue.host_and_port.DATACATALOGUE_GRPC_PORT=5052
datacatalogue.logger.comment="Logger settings"
datacatalogue.logger.DATACATALOGUE_LOGGER_LEVEL="info"
datacatalogue.logger.DATACATALOGUE_LOGGER_AS_JSON="true"
datacatalogue.db.comment="Postgres DB settings"
datacatalogue.db.DATACATALOGUE_CONTAINER_NAME="datacomradepostgres"
datacatalogue.db.DATACATALOGUE_POSTGRES_IMAGE="postgres:18.3-alpine3.23"
datacatalogue.db.DATACATALOGUE_POSTGRES_USER="postgres_user"
datacatalogue.db.DATACATALOGUE_POSTGRES_PASSWORD="pass"
datacatalogue.db.DATACATALOGUE_POSTGRES_HOST="localhost"
datacatalogue.db.DATACATALOGUE_POSTGRES_PORT=5432
datacatalogue.db.DATACATALOGUE_POSTGRES_DB="dcat"
datacatalogue.db.DB_MAX_OPEN_CONNS=50
datacatalogue.db.DB_MAX_IDLE_CONNS=50
datacatalogue.db.DB_MAX_IDLE_TIME_MINS=5
datacatalogue.goose.comment="Миграции в go/goose"
datacatalogue.goose.GOOSE_DRIVER="postgres"
datacatalogue.goose.GOOSE_DBSTRING="postgres://postgres_user:pass@localhost:5432/dcat"
datacatalogue.goose.GOOSE_MIGRATION_DIR="./db/migrations"
datacatalogue.goose.GOOSE_TABLE="tech.goose_migrations"
