// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package rolesmodel

import (
	"database/sql"
	"time"
)

type UsersAction struct {
	ID          int64
	Name        string
	Description string
	IsDeleted   bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type UsersResource struct {
	ID          int64
	Name        string
	Description string
	IsDeleted   bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type UsersResourceType struct {
	ID          int64
	Name        string
	Description string
	IsDeleted   bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type UsersRole struct {
	ID            int64
	RoleNameLong  string
	RoleNameShort string
	Description   sql.NullString
	JwtExport     bool
	IsDeleted     bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type UsersRoleAccess struct {
	ID             int64
	RoleID         int64
	ResourceID     int64
	ActionID       int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	IsDeleted      bool
	ResourceTypeID int64
}

type UsersUserAccess struct {
	ID             int64
	UserID         int64
	ResourceID     int64
	ActionID       int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	IsDeleted      bool
	ResourceTypeID int64
}

type UsersUserRole struct {
	ID        int64
	UserID    int64
	RoleID    int64
	IsDeleted bool
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}
