// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package rolesmodel

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type UsersAction struct {
	ID          int64
	Name        string
	Description string
	IsDeleted   bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type UsersResource struct {
	ID          int64
	Name        string
	Description string
	IsDeleted   bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type UsersRole struct {
	ID            int64
	RoleNameLong  string
	RoleNameShort string
	Description   *string
	JwtExport     bool
	IsDeleted     bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type UsersRoleAccess struct {
	ID             int64
	RoleID         int64
	ResourceID     int64
	ActionID       int64
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	IsDeleted      bool
	ResourceTypeID int64
}

type UsersUserAccess struct {
	ID             int64
	UserID         int64
	ResourceID     int64
	ActionID       int64
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	IsDeleted      bool
	ResourceTypeID int64
}

type UsersUserRole struct {
	ID        int64
	UserID    int64
	RoleID    int64
	IsDeleted bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
