// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package user_model

import (
	"time"

	"github.com/google/uuid"
)

type DcUser struct {
	ID         int64
	Name       string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	IsDeleted  bool
	ExternalID uuid.UUID
}
