// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package user_model

import (
	"time"
)

type DcUser struct {
	ID             int64
	Name           string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	IsDeleted      bool
	IncomingUserID int64
}
