// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package user_model

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO dc."user"
("name", external_id, is_deleted, created_at, updated_at)
VALUES($1, $2, false, now(), now())
RETURNING id, name, created_at, updated_at, is_deleted, external_id
`

type CreateUserParams struct {
	Name       string
	ExternalID uuid.UUID
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (DcUser, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Name, arg.ExternalID)
	var i DcUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.ExternalID,
	)
	return i, err
}

const deleteUserById = `-- name: DeleteUserById :exec
UPDATE dc."user"
SET is_deleted=true, updated_at=now()
WHERE id=$1
`

func (q *Queries) DeleteUserById(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserById, id)
	return err
}

const getDeletedUserById = `-- name: GetDeletedUserById :one
SELECT id, name, created_at, updated_at, is_deleted, external_id
FROM dc."user"
WHERE id = $1
AND is_deleted = true
`

func (q *Queries) GetDeletedUserById(ctx context.Context, id int64) (DcUser, error) {
	row := q.db.QueryRowContext(ctx, getDeletedUserById, id)
	var i DcUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.ExternalID,
	)
	return i, err
}

const getDeletedUsers = `-- name: GetDeletedUsers :many
SELECT id, name, created_at, updated_at, is_deleted, external_id
FROM dc."user"
WHERE is_deleted = true
ORDER BY id
`

func (q *Queries) GetDeletedUsers(ctx context.Context) ([]DcUser, error) {
	rows, err := q.db.QueryContext(ctx, getDeletedUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DcUser
	for rows.Next() {
		var i DcUser
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
			&i.ExternalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByExternalId = `-- name: GetUserByExternalId :one
SELECT id, name, created_at, updated_at, is_deleted, external_id
FROM dc."user"
WHERE external_id = $1
AND is_deleted = false
`

func (q *Queries) GetUserByExternalId(ctx context.Context, externalID uuid.UUID) (DcUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByExternalId, externalID)
	var i DcUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.ExternalID,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one

SELECT id, name, created_at, updated_at, is_deleted, external_id
FROM dc."user"
WHERE id = $1
AND is_deleted = false
`

// =========================================================
// dc.user
// =========================================================
func (q *Queries) GetUserById(ctx context.Context, id int64) (DcUser, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i DcUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.ExternalID,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, name, created_at, updated_at, is_deleted, external_id
FROM dc."user"
WHERE is_deleted = false
ORDER BY id
`

func (q *Queries) GetUsers(ctx context.Context) ([]DcUser, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DcUser
	for rows.Next() {
		var i DcUser
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
			&i.ExternalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const undeleteUserById = `-- name: UndeleteUserById :exec
UPDATE dc."user"
SET is_deleted=false, updated_at=now()
WHERE id=$1
`

func (q *Queries) UndeleteUserById(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, undeleteUserById, id)
	return err
}

const updateUserById = `-- name: UpdateUserById :one
UPDATE dc."user"
SET "name"=$2, external_id=$3, updated_at=now()
WHERE id=$1
AND is_deleted = false
RETURNING id, name, created_at, updated_at, is_deleted, external_id
`

type UpdateUserByIdParams struct {
	ID         int64
	Name       string
	ExternalID uuid.UUID
}

func (q *Queries) UpdateUserById(ctx context.Context, arg UpdateUserByIdParams) (DcUser, error) {
	row := q.db.QueryRowContext(ctx, updateUserById, arg.ID, arg.Name, arg.ExternalID)
	var i DcUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.ExternalID,
	)
	return i, err
}
