// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package tables_model

import (
	"context"

	"github.com/google/uuid"
)

const countGetAliases = `-- name: CountGetAliases :one
SELECT
    count(*)                                                        AS total_items,
    ceil(count(*)::numeric / GREATEST($1::int, 1))::bigint AS total_pages
FROM dc.alias
WHERE alias.is_deleted = false
`

type CountGetAliasesRow struct {
	TotalItems int64
	TotalPages int64
}

func (q *Queries) CountGetAliases(ctx context.Context, pageLimit int32) (CountGetAliasesRow, error) {
	row := q.db.QueryRowContext(ctx, countGetAliases, pageLimit)
	var i CountGetAliasesRow
	err := row.Scan(&i.TotalItems, &i.TotalPages)
	return i, err
}

const countGetAliasesDeleted = `-- name: CountGetAliasesDeleted :one
SELECT
    count(*)                                                        AS total_items,
    ceil(count(*)::numeric / GREATEST($1::int, 1))::bigint AS total_pages
FROM dc.alias
WHERE alias.is_deleted = true
`

type CountGetAliasesDeletedRow struct {
	TotalItems int64
	TotalPages int64
}

func (q *Queries) CountGetAliasesDeleted(ctx context.Context, pageLimit int32) (CountGetAliasesDeletedRow, error) {
	row := q.db.QueryRowContext(ctx, countGetAliasesDeleted, pageLimit)
	var i CountGetAliasesDeletedRow
	err := row.Scan(&i.TotalItems, &i.TotalPages)
	return i, err
}

const countGetHostDeleted = `-- name: CountGetHostDeleted :one
SELECT
    count(*)                                                        AS total_items,
    ceil(count(*)::numeric / GREATEST($1::int, 1))::bigint AS total_pages
FROM dc.host
WHERE host.is_deleted = true
`

type CountGetHostDeletedRow struct {
	TotalItems int64
	TotalPages int64
}

func (q *Queries) CountGetHostDeleted(ctx context.Context, pageLimit int32) (CountGetHostDeletedRow, error) {
	row := q.db.QueryRowContext(ctx, countGetHostDeleted, pageLimit)
	var i CountGetHostDeletedRow
	err := row.Scan(&i.TotalItems, &i.TotalPages)
	return i, err
}

const countGetHosts = `-- name: CountGetHosts :one
SELECT
    count(*)                                                        AS total_items,
    ceil(count(*)::numeric / GREATEST($1::int, 1))::bigint AS total_pages
FROM dc.host
WHERE host.is_deleted = false
`

type CountGetHostsRow struct {
	TotalItems int64
	TotalPages int64
}

func (q *Queries) CountGetHosts(ctx context.Context, pageLimit int32) (CountGetHostsRow, error) {
	row := q.db.QueryRowContext(ctx, countGetHosts, pageLimit)
	var i CountGetHostsRow
	err := row.Scan(&i.TotalItems, &i.TotalPages)
	return i, err
}

const countGetHostsSearchName = `-- name: CountGetHostsSearchName :one
SELECT
    count(*)                                                        AS total_items,
    ceil(count(*)::numeric / GREATEST($1::int, 1))::bigint AS total_pages
FROM dc.host
WHERE host.is_deleted = false
  AND (lower(name) LIKE '%' || lower($2) || '%')
`

type CountGetHostsSearchNameParams struct {
	PageLimit  int32
	SearchName string
}

type CountGetHostsSearchNameRow struct {
	TotalItems int64
	TotalPages int64
}

func (q *Queries) CountGetHostsSearchName(ctx context.Context, arg CountGetHostsSearchNameParams) (CountGetHostsSearchNameRow, error) {
	row := q.db.QueryRowContext(ctx, countGetHostsSearchName, arg.PageLimit, arg.SearchName)
	var i CountGetHostsSearchNameRow
	err := row.Scan(&i.TotalItems, &i.TotalPages)
	return i, err
}

const countGetUsers = `-- name: CountGetUsers :one
SELECT
    count(*)                                                        AS total_items,
    ceil(count(*)::numeric / GREATEST($1::int, 1))::bigint AS total_pages
FROM dc."user"
WHERE "user".is_deleted = false
`

type CountGetUsersRow struct {
	TotalItems int64
	TotalPages int64
}

func (q *Queries) CountGetUsers(ctx context.Context, pageLimit int32) (CountGetUsersRow, error) {
	row := q.db.QueryRowContext(ctx, countGetUsers, pageLimit)
	var i CountGetUsersRow
	err := row.Scan(&i.TotalItems, &i.TotalPages)
	return i, err
}

const createAlias = `-- name: CreateAlias :one


INSERT INTO dc.alias (
    name,
    description,
    created_at,
    updated_at,
    is_deleted,
    user_id
) VALUES (
    $1,
    $2,
    now(),
    now(),
    false,
    (SELECT u.id FROM dc."user" u WHERE u.external_id = $3)
)
RETURNING id, name, description, created_at, updated_at, is_deleted, user_id
`

type CreateAliasParams struct {
	Name        string
	Description string
	ExternalID  uuid.UUID
}

// Файл сгенерирован программой SG Buddy https://github.com/konstantin-suspitsyn/sg_buddy
// Правки будут затёрты при следующей генерации: правьте настройки, а не этот файл.
// =========================================================
// dc.alias
// =========================================================
func (q *Queries) CreateAlias(ctx context.Context, arg CreateAliasParams) (DcAlias, error) {
	row := q.db.QueryRowContext(ctx, createAlias, arg.Name, arg.Description, arg.ExternalID)
	var i DcAlias
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.UserID,
	)
	return i, err
}

const createHost = `-- name: CreateHost :one

INSERT INTO dc.host (
    name,
    description,
    host_env,
    port_env,
    username_env,
    password_env,
    is_deleted,
    created_at,
    updated_at,
    user_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    false,
    now(),
    now(),
    (SELECT u.id FROM dc."user" u WHERE u.external_id = $7)
)
RETURNING id, name, description, host_env, port_env, username_env, password_env, is_deleted, created_at, updated_at, user_id
`

type CreateHostParams struct {
	Name        string
	Description string
	HostEnv     string
	PortEnv     string
	UsernameEnv string
	PasswordEnv string
	ExternalID  uuid.UUID
}

// =========================================================
// dc.host
// =========================================================
func (q *Queries) CreateHost(ctx context.Context, arg CreateHostParams) (DcHost, error) {
	row := q.db.QueryRowContext(ctx, createHost,
		arg.Name,
		arg.Description,
		arg.HostEnv,
		arg.PortEnv,
		arg.UsernameEnv,
		arg.PasswordEnv,
		arg.ExternalID,
	)
	var i DcHost
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.HostEnv,
		&i.PortEnv,
		&i.UsernameEnv,
		&i.PasswordEnv,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO dc."user" (
    name,
    created_at,
    updated_at,
    is_deleted,
    external_id
) VALUES (
    $1,
    now(),
    now(),
    false,
    $2
)
RETURNING id, name, created_at, updated_at, is_deleted, external_id
`

type CreateUserParams struct {
	Name       string
	ExternalID uuid.UUID
}

// =========================================================
// dc."user"
// =========================================================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (DcUser, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Name, arg.ExternalID)
	var i DcUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.ExternalID,
	)
	return i, err
}

const deleteAliasById = `-- name: DeleteAliasById :exec
UPDATE dc.alias
SET updated_at = now(),
    is_deleted = true,
    user_id = (SELECT u.id FROM dc."user" u WHERE u.external_id = $1)
WHERE alias.id = $2
`

type DeleteAliasByIdParams struct {
	ExternalID uuid.UUID
	ID         int64
}

func (q *Queries) DeleteAliasById(ctx context.Context, arg DeleteAliasByIdParams) error {
	_, err := q.db.ExecContext(ctx, deleteAliasById, arg.ExternalID, arg.ID)
	return err
}

const deleteHostById = `-- name: DeleteHostById :exec
UPDATE dc.host
SET is_deleted = true,
    updated_at = now(),
    user_id = (SELECT u.id FROM dc."user" u WHERE u.external_id = $1)
WHERE host.id = $2
`

type DeleteHostByIdParams struct {
	ExternalID uuid.UUID
	ID         int64
}

func (q *Queries) DeleteHostById(ctx context.Context, arg DeleteHostByIdParams) error {
	_, err := q.db.ExecContext(ctx, deleteHostById, arg.ExternalID, arg.ID)
	return err
}

const getAliasById = `-- name: GetAliasById :one
SELECT
    alias.id,
    alias.name,
    alias.description,
    alias.created_at,
    alias.updated_at,
    alias.is_deleted,
    alias.user_id
FROM dc.alias
WHERE alias.id = $1
  AND alias.is_deleted = false
LIMIT 1
`

func (q *Queries) GetAliasById(ctx context.Context, id int64) (DcAlias, error) {
	row := q.db.QueryRowContext(ctx, getAliasById, id)
	var i DcAlias
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.UserID,
	)
	return i, err
}

const getAliases = `-- name: GetAliases :many
SELECT
    alias.id,
    alias.name,
    alias.description,
    alias.created_at,
    alias.updated_at,
    alias.is_deleted,
    alias.user_id
FROM dc.alias
WHERE alias.is_deleted = false
ORDER BY CASE WHEN $1::text <> 'DESC' THEN alias.id END ASC,
    CASE WHEN $1::text = 'DESC' THEN alias.id END DESC
LIMIT $3::int OFFSET ($2::int-1)*$3::int
`

type GetAliasesParams struct {
	Order     string
	Page      int32
	PageLimit int32
}

func (q *Queries) GetAliases(ctx context.Context, arg GetAliasesParams) ([]DcAlias, error) {
	rows, err := q.db.QueryContext(ctx, getAliases, arg.Order, arg.Page, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DcAlias
	for rows.Next() {
		var i DcAlias
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAliasesDeleted = `-- name: GetAliasesDeleted :many
SELECT
    alias.id,
    alias.name,
    alias.description,
    alias.created_at,
    alias.updated_at,
    alias.is_deleted,
    alias.user_id
FROM dc.alias
WHERE alias.is_deleted = true
ORDER BY CASE WHEN $1::text <> 'DESC' THEN alias.id END ASC,
    CASE WHEN $1::text = 'DESC' THEN alias.id END DESC
LIMIT $3::int OFFSET ($2::int-1)*$3::int
`

type GetAliasesDeletedParams struct {
	Order     string
	Page      int32
	PageLimit int32
}

func (q *Queries) GetAliasesDeleted(ctx context.Context, arg GetAliasesDeletedParams) ([]DcAlias, error) {
	rows, err := q.db.QueryContext(ctx, getAliasesDeleted, arg.Order, arg.Page, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DcAlias
	for rows.Next() {
		var i DcAlias
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHostById = `-- name: GetHostById :one
SELECT
    host.id,
    host.name,
    host.description,
    host.host_env,
    host.port_env,
    host.username_env,
    host.password_env,
    host.is_deleted,
    host.created_at,
    host.updated_at,
    host.user_id
FROM dc.host
WHERE host.id = $1
LIMIT 1
`

func (q *Queries) GetHostById(ctx context.Context, id int64) (DcHost, error) {
	row := q.db.QueryRowContext(ctx, getHostById, id)
	var i DcHost
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.HostEnv,
		&i.PortEnv,
		&i.UsernameEnv,
		&i.PasswordEnv,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getHostDeleted = `-- name: GetHostDeleted :many
SELECT
    host.id,
    host.name,
    host.description,
    host.host_env,
    host.port_env,
    host.username_env,
    host.password_env,
    host.is_deleted,
    host.created_at,
    host.updated_at,
    host.user_id
FROM dc.host
WHERE host.is_deleted = true
ORDER BY CASE WHEN $1::text <> 'DESC' THEN host.id END ASC,
    CASE WHEN $1::text = 'DESC' THEN host.id END DESC
LIMIT $3::int OFFSET ($2::int-1)*$3::int
`

type GetHostDeletedParams struct {
	Order     string
	Page      int32
	PageLimit int32
}

func (q *Queries) GetHostDeleted(ctx context.Context, arg GetHostDeletedParams) ([]DcHost, error) {
	rows, err := q.db.QueryContext(ctx, getHostDeleted, arg.Order, arg.Page, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DcHost
	for rows.Next() {
		var i DcHost
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.HostEnv,
			&i.PortEnv,
			&i.UsernameEnv,
			&i.PasswordEnv,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHosts = `-- name: GetHosts :many
SELECT
    host.id,
    host.name,
    host.description,
    host.host_env,
    host.port_env,
    host.username_env,
    host.password_env,
    host.is_deleted,
    host.created_at,
    host.updated_at,
    host.user_id
FROM dc.host
WHERE host.is_deleted = false
ORDER BY CASE WHEN $1::text <> 'DESC' THEN host.id END ASC,
    CASE WHEN $1::text = 'DESC' THEN host.id END DESC
LIMIT $3::int OFFSET ($2::int-1)*$3::int
`

type GetHostsParams struct {
	Order     string
	Page      int32
	PageLimit int32
}

func (q *Queries) GetHosts(ctx context.Context, arg GetHostsParams) ([]DcHost, error) {
	rows, err := q.db.QueryContext(ctx, getHosts, arg.Order, arg.Page, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DcHost
	for rows.Next() {
		var i DcHost
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.HostEnv,
			&i.PortEnv,
			&i.UsernameEnv,
			&i.PasswordEnv,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHostsSearchName = `-- name: GetHostsSearchName :many
SELECT
    host.id,
    host.name,
    host.description,
    host.host_env,
    host.port_env,
    host.username_env,
    host.password_env,
    host.is_deleted,
    host.created_at,
    host.updated_at,
    host.user_id
FROM dc.host
WHERE host.is_deleted = false
  AND (lower(name) LIKE '%' || lower($1) || '%')
ORDER BY CASE WHEN $2::text <> 'DESC' THEN host.id END ASC,
    CASE WHEN $2::text = 'DESC' THEN host.id END DESC
LIMIT $4::int OFFSET ($3::int-1)*$4::int
`

type GetHostsSearchNameParams struct {
	SearchName string
	Order      string
	Page       int32
	PageLimit  int32
}

func (q *Queries) GetHostsSearchName(ctx context.Context, arg GetHostsSearchNameParams) ([]DcHost, error) {
	rows, err := q.db.QueryContext(ctx, getHostsSearchName,
		arg.SearchName,
		arg.Order,
		arg.Page,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DcHost
	for rows.Next() {
		var i DcHost
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.HostEnv,
			&i.PortEnv,
			&i.UsernameEnv,
			&i.PasswordEnv,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByExternalId = `-- name: GetUserByExternalId :one
SELECT
    "user".id,
    "user".name,
    "user".created_at,
    "user".updated_at,
    "user".is_deleted,
    "user".external_id
FROM dc."user"
WHERE "user".is_deleted = false
  AND "user".external_id = $1
LIMIT 1
`

func (q *Queries) GetUserByExternalId(ctx context.Context, externalID uuid.UUID) (DcUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByExternalId, externalID)
	var i DcUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.ExternalID,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT
    "user".id,
    "user".name,
    "user".created_at,
    "user".updated_at,
    "user".is_deleted,
    "user".external_id
FROM dc."user"
WHERE "user".is_deleted = false
ORDER BY CASE WHEN $1::text <> 'DESC' THEN "user".id END ASC,
    CASE WHEN $1::text = 'DESC' THEN "user".id END DESC
LIMIT $3::int OFFSET ($2::int-1)*$3::int
`

type GetUsersParams struct {
	Order     string
	Page      int32
	PageLimit int32
}

func (q *Queries) GetUsers(ctx context.Context, arg GetUsersParams) ([]DcUser, error) {
	rows, err := q.db.QueryContext(ctx, getUsers, arg.Order, arg.Page, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DcUser
	for rows.Next() {
		var i DcUser
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
			&i.ExternalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const undeleteAliasById = `-- name: UndeleteAliasById :exec
UPDATE dc.alias
SET updated_at = now(),
    is_deleted = false,
    user_id = (SELECT u.id FROM dc."user" u WHERE u.external_id = $1)
WHERE alias.id = $2
`

type UndeleteAliasByIdParams struct {
	ExternalID uuid.UUID
	ID         int64
}

func (q *Queries) UndeleteAliasById(ctx context.Context, arg UndeleteAliasByIdParams) error {
	_, err := q.db.ExecContext(ctx, undeleteAliasById, arg.ExternalID, arg.ID)
	return err
}

const undeleteHostById = `-- name: UndeleteHostById :exec
UPDATE dc.host
SET is_deleted = false,
    updated_at = now(),
    user_id = (SELECT u.id FROM dc."user" u WHERE u.external_id = $1)
WHERE host.id = $2
`

type UndeleteHostByIdParams struct {
	ExternalID uuid.UUID
	ID         int64
}

func (q *Queries) UndeleteHostById(ctx context.Context, arg UndeleteHostByIdParams) error {
	_, err := q.db.ExecContext(ctx, undeleteHostById, arg.ExternalID, arg.ID)
	return err
}

const updateAliasById = `-- name: UpdateAliasById :exec
UPDATE dc.alias
SET name = $1,
    description = $2,
    updated_at = now(),
    is_deleted = $3,
    user_id = (SELECT u.id FROM dc."user" u WHERE u.external_id = $4)
WHERE alias.id = $5
`

type UpdateAliasByIdParams struct {
	Name        string
	Description string
	IsDeleted   bool
	ExternalID  uuid.UUID
	ID          int64
}

func (q *Queries) UpdateAliasById(ctx context.Context, arg UpdateAliasByIdParams) error {
	_, err := q.db.ExecContext(ctx, updateAliasById,
		arg.Name,
		arg.Description,
		arg.IsDeleted,
		arg.ExternalID,
		arg.ID,
	)
	return err
}

const updateHostById = `-- name: UpdateHostById :exec
UPDATE dc.host
SET id = $1,
    name = $2,
    description = $3,
    host_env = $4,
    port_env = $5,
    username_env = $6,
    password_env = $7,
    is_deleted = false,
    updated_at = now(),
    user_id = (SELECT u.id FROM dc."user" u WHERE u.external_id = $8)
WHERE host.id = $1
`

type UpdateHostByIdParams struct {
	ID          int64
	Name        string
	Description string
	HostEnv     string
	PortEnv     string
	UsernameEnv string
	PasswordEnv string
	ExternalID  uuid.UUID
}

func (q *Queries) UpdateHostById(ctx context.Context, arg UpdateHostByIdParams) error {
	_, err := q.db.ExecContext(ctx, updateHostById,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.HostEnv,
		arg.PortEnv,
		arg.UsernameEnv,
		arg.PasswordEnv,
		arg.ExternalID,
	)
	return err
}
