// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: auth_logic/v1/auth_logic.proto

package authlogicv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthLogicService_GetTableIdsByExternalUserIdAndRoles_FullMethodName = "/auth_logic.v1.AuthLogicService/GetTableIdsByExternalUserIdAndRoles"
	AuthLogicService_GetTableIdsByUserIdAndRoles_FullMethodName         = "/auth_logic.v1.AuthLogicService/GetTableIdsByUserIdAndRoles"
)

// AuthLogicServiceClient is the client API for AuthLogicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthLogicService mirrors query.sql one-to-one: table-id lookups by user and role.
type AuthLogicServiceClient interface {
	// dc.table_cat
	GetTableIdsByExternalUserIdAndRoles(ctx context.Context, in *GetTableIdsByExternalUserIdAndRolesRequest, opts ...grpc.CallOption) (*GetTableIdsByExternalUserIdAndRolesResponse, error)
	GetTableIdsByUserIdAndRoles(ctx context.Context, in *GetTableIdsByUserIdAndRolesRequest, opts ...grpc.CallOption) (*GetTableIdsByUserIdAndRolesResponse, error)
}

type authLogicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthLogicServiceClient(cc grpc.ClientConnInterface) AuthLogicServiceClient {
	return &authLogicServiceClient{cc}
}

func (c *authLogicServiceClient) GetTableIdsByExternalUserIdAndRoles(ctx context.Context, in *GetTableIdsByExternalUserIdAndRolesRequest, opts ...grpc.CallOption) (*GetTableIdsByExternalUserIdAndRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTableIdsByExternalUserIdAndRolesResponse)
	err := c.cc.Invoke(ctx, AuthLogicService_GetTableIdsByExternalUserIdAndRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authLogicServiceClient) GetTableIdsByUserIdAndRoles(ctx context.Context, in *GetTableIdsByUserIdAndRolesRequest, opts ...grpc.CallOption) (*GetTableIdsByUserIdAndRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTableIdsByUserIdAndRolesResponse)
	err := c.cc.Invoke(ctx, AuthLogicService_GetTableIdsByUserIdAndRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthLogicServiceServer is the server API for AuthLogicService service.
// All implementations must embed UnimplementedAuthLogicServiceServer
// for forward compatibility.
//
// AuthLogicService mirrors query.sql one-to-one: table-id lookups by user and role.
type AuthLogicServiceServer interface {
	// dc.table_cat
	GetTableIdsByExternalUserIdAndRoles(context.Context, *GetTableIdsByExternalUserIdAndRolesRequest) (*GetTableIdsByExternalUserIdAndRolesResponse, error)
	GetTableIdsByUserIdAndRoles(context.Context, *GetTableIdsByUserIdAndRolesRequest) (*GetTableIdsByUserIdAndRolesResponse, error)
	mustEmbedUnimplementedAuthLogicServiceServer()
}

// UnimplementedAuthLogicServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthLogicServiceServer struct{}

func (UnimplementedAuthLogicServiceServer) GetTableIdsByExternalUserIdAndRoles(context.Context, *GetTableIdsByExternalUserIdAndRolesRequest) (*GetTableIdsByExternalUserIdAndRolesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTableIdsByExternalUserIdAndRoles not implemented")
}
func (UnimplementedAuthLogicServiceServer) GetTableIdsByUserIdAndRoles(context.Context, *GetTableIdsByUserIdAndRolesRequest) (*GetTableIdsByUserIdAndRolesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTableIdsByUserIdAndRoles not implemented")
}
func (UnimplementedAuthLogicServiceServer) mustEmbedUnimplementedAuthLogicServiceServer() {}
func (UnimplementedAuthLogicServiceServer) testEmbeddedByValue()                          {}

// UnsafeAuthLogicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthLogicServiceServer will
// result in compilation errors.
type UnsafeAuthLogicServiceServer interface {
	mustEmbedUnimplementedAuthLogicServiceServer()
}

func RegisterAuthLogicServiceServer(s grpc.ServiceRegistrar, srv AuthLogicServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuthLogicServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthLogicService_ServiceDesc, srv)
}

func _AuthLogicService_GetTableIdsByExternalUserIdAndRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTableIdsByExternalUserIdAndRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthLogicServiceServer).GetTableIdsByExternalUserIdAndRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthLogicService_GetTableIdsByExternalUserIdAndRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthLogicServiceServer).GetTableIdsByExternalUserIdAndRoles(ctx, req.(*GetTableIdsByExternalUserIdAndRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthLogicService_GetTableIdsByUserIdAndRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTableIdsByUserIdAndRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthLogicServiceServer).GetTableIdsByUserIdAndRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthLogicService_GetTableIdsByUserIdAndRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthLogicServiceServer).GetTableIdsByUserIdAndRoles(ctx, req.(*GetTableIdsByUserIdAndRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthLogicService_ServiceDesc is the grpc.ServiceDesc for AuthLogicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthLogicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth_logic.v1.AuthLogicService",
	HandlerType: (*AuthLogicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTableIdsByExternalUserIdAndRoles",
			Handler:    _AuthLogicService_GetTableIdsByExternalUserIdAndRoles_Handler,
		},
		{
			MethodName: "GetTableIdsByUserIdAndRoles",
			Handler:    _AuthLogicService_GetTableIdsByUserIdAndRoles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth_logic/v1/auth_logic.proto",
}
