// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: auth_logic/v1/auth_logic.proto

package authlogicv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetTableIdsByExternalUserIdAndRolesRequest carries the external user id and role name used to look up accessible dc.table_cat ids (query GetTableIdsByExternalUserIdAndRoles).
type GetTableIdsByExternalUserIdAndRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTableIdsByExternalUserIdAndRolesRequest) Reset() {
	*x = GetTableIdsByExternalUserIdAndRolesRequest{}
	mi := &file_auth_logic_v1_auth_logic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTableIdsByExternalUserIdAndRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableIdsByExternalUserIdAndRolesRequest) ProtoMessage() {}

func (x *GetTableIdsByExternalUserIdAndRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_logic_v1_auth_logic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableIdsByExternalUserIdAndRolesRequest.ProtoReflect.Descriptor instead.
func (*GetTableIdsByExternalUserIdAndRolesRequest) Descriptor() ([]byte, []int) {
	return file_auth_logic_v1_auth_logic_proto_rawDescGZIP(), []int{0}
}

func (x *GetTableIdsByExternalUserIdAndRolesRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *GetTableIdsByExternalUserIdAndRolesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetTableIdsByExternalUserIdAndRolesResponse returns the dc.table_cat ids accessible to the user (query GetTableIdsByExternalUserIdAndRoles).
type GetTableIdsByExternalUserIdAndRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableIds      []int64                `protobuf:"varint,1,rep,packed,name=table_ids,json=tableIds,proto3" json:"table_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTableIdsByExternalUserIdAndRolesResponse) Reset() {
	*x = GetTableIdsByExternalUserIdAndRolesResponse{}
	mi := &file_auth_logic_v1_auth_logic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTableIdsByExternalUserIdAndRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableIdsByExternalUserIdAndRolesResponse) ProtoMessage() {}

func (x *GetTableIdsByExternalUserIdAndRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_logic_v1_auth_logic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableIdsByExternalUserIdAndRolesResponse.ProtoReflect.Descriptor instead.
func (*GetTableIdsByExternalUserIdAndRolesResponse) Descriptor() ([]byte, []int) {
	return file_auth_logic_v1_auth_logic_proto_rawDescGZIP(), []int{1}
}

func (x *GetTableIdsByExternalUserIdAndRolesResponse) GetTableIds() []int64 {
	if x != nil {
		return x.TableIds
	}
	return nil
}

// GetTableIdsByUserIdAndRolesRequest carries the user id and role name used to look up accessible dc.table_cat ids (query GetTableIdsByUserIdAndRoles).
type GetTableIdsByUserIdAndRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTableIdsByUserIdAndRolesRequest) Reset() {
	*x = GetTableIdsByUserIdAndRolesRequest{}
	mi := &file_auth_logic_v1_auth_logic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTableIdsByUserIdAndRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableIdsByUserIdAndRolesRequest) ProtoMessage() {}

func (x *GetTableIdsByUserIdAndRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_logic_v1_auth_logic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableIdsByUserIdAndRolesRequest.ProtoReflect.Descriptor instead.
func (*GetTableIdsByUserIdAndRolesRequest) Descriptor() ([]byte, []int) {
	return file_auth_logic_v1_auth_logic_proto_rawDescGZIP(), []int{2}
}

func (x *GetTableIdsByUserIdAndRolesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetTableIdsByUserIdAndRolesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetTableIdsByUserIdAndRolesResponse returns the dc.table_cat ids accessible to the user (query GetTableIdsByUserIdAndRoles).
type GetTableIdsByUserIdAndRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableIds      []int64                `protobuf:"varint,1,rep,packed,name=table_ids,json=tableIds,proto3" json:"table_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTableIdsByUserIdAndRolesResponse) Reset() {
	*x = GetTableIdsByUserIdAndRolesResponse{}
	mi := &file_auth_logic_v1_auth_logic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTableIdsByUserIdAndRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableIdsByUserIdAndRolesResponse) ProtoMessage() {}

func (x *GetTableIdsByUserIdAndRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_logic_v1_auth_logic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableIdsByUserIdAndRolesResponse.ProtoReflect.Descriptor instead.
func (*GetTableIdsByUserIdAndRolesResponse) Descriptor() ([]byte, []int) {
	return file_auth_logic_v1_auth_logic_proto_rawDescGZIP(), []int{3}
}

func (x *GetTableIdsByUserIdAndRolesResponse) GetTableIds() []int64 {
	if x != nil {
		return x.TableIds
	}
	return nil
}

var File_auth_logic_v1_auth_logic_proto protoreflect.FileDescriptor

const file_auth_logic_v1_auth_logic_proto_rawDesc = "" +
	"\n" +
	"\x1eauth_logic/v1/auth_logic.proto\x12\rauth_logic.v1\"a\n" +
	"*GetTableIdsByExternalUserIdAndRolesRequest\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"J\n" +
	"+GetTableIdsByExternalUserIdAndRolesResponse\x12\x1b\n" +
	"\ttable_ids\x18\x01 \x03(\x03R\btableIds\"Q\n" +
	"\"GetTableIdsByUserIdAndRolesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"B\n" +
	"#GetTableIdsByUserIdAndRolesResponse\x12\x1b\n" +
	"\ttable_ids\x18\x01 \x03(\x03R\btableIds2\xb8\x02\n" +
	"\x10AuthLogicService\x12\x9c\x01\n" +
	"#GetTableIdsByExternalUserIdAndRoles\x129.auth_logic.v1.GetTableIdsByExternalUserIdAndRolesRequest\x1a:.auth_logic.v1.GetTableIdsByExternalUserIdAndRolesResponse\x12\x84\x01\n" +
	"\x1bGetTableIdsByUserIdAndRoles\x121.auth_logic.v1.GetTableIdsByUserIdAndRolesRequest\x1a2.auth_logic.v1.GetTableIdsByUserIdAndRolesResponseBXZVgithub.com/konstantin-suspitsyn/datacomrade/shared/pkg/proto/auth_logic/v1;authlogicv1b\x06proto3"

var (
	file_auth_logic_v1_auth_logic_proto_rawDescOnce sync.Once
	file_auth_logic_v1_auth_logic_proto_rawDescData []byte
)

func file_auth_logic_v1_auth_logic_proto_rawDescGZIP() []byte {
	file_auth_logic_v1_auth_logic_proto_rawDescOnce.Do(func() {
		file_auth_logic_v1_auth_logic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_logic_v1_auth_logic_proto_rawDesc), len(file_auth_logic_v1_auth_logic_proto_rawDesc)))
	})
	return file_auth_logic_v1_auth_logic_proto_rawDescData
}

var file_auth_logic_v1_auth_logic_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_auth_logic_v1_auth_logic_proto_goTypes = []any{
	(*GetTableIdsByExternalUserIdAndRolesRequest)(nil),  // 0: auth_logic.v1.GetTableIdsByExternalUserIdAndRolesRequest
	(*GetTableIdsByExternalUserIdAndRolesResponse)(nil), // 1: auth_logic.v1.GetTableIdsByExternalUserIdAndRolesResponse
	(*GetTableIdsByUserIdAndRolesRequest)(nil),          // 2: auth_logic.v1.GetTableIdsByUserIdAndRolesRequest
	(*GetTableIdsByUserIdAndRolesResponse)(nil),         // 3: auth_logic.v1.GetTableIdsByUserIdAndRolesResponse
}
var file_auth_logic_v1_auth_logic_proto_depIdxs = []int32{
	0, // 0: auth_logic.v1.AuthLogicService.GetTableIdsByExternalUserIdAndRoles:input_type -> auth_logic.v1.GetTableIdsByExternalUserIdAndRolesRequest
	2, // 1: auth_logic.v1.AuthLogicService.GetTableIdsByUserIdAndRoles:input_type -> auth_logic.v1.GetTableIdsByUserIdAndRolesRequest
	1, // 2: auth_logic.v1.AuthLogicService.GetTableIdsByExternalUserIdAndRoles:output_type -> auth_logic.v1.GetTableIdsByExternalUserIdAndRolesResponse
	3, // 3: auth_logic.v1.AuthLogicService.GetTableIdsByUserIdAndRoles:output_type -> auth_logic.v1.GetTableIdsByUserIdAndRolesResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_logic_v1_auth_logic_proto_init() }
func file_auth_logic_v1_auth_logic_proto_init() {
	if File_auth_logic_v1_auth_logic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_logic_v1_auth_logic_proto_rawDesc), len(file_auth_logic_v1_auth_logic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_logic_v1_auth_logic_proto_goTypes,
		DependencyIndexes: file_auth_logic_v1_auth_logic_proto_depIdxs,
		MessageInfos:      file_auth_logic_v1_auth_logic_proto_msgTypes,
	}.Build()
	File_auth_logic_v1_auth_logic_proto = out.File
	file_auth_logic_v1_auth_logic_proto_goTypes = nil
	file_auth_logic_v1_auth_logic_proto_depIdxs = nil
}
