// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package user_domain_roles

import (
	"time"
)

type DcDomainRole struct {
	ID          int64
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	IsDeleted   bool
}

type DcDomainsDomainRole struct {
	ID            int64
	DomainCatID   int64
	DomainRolesID int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	IsDeleted     bool
}

type DcTableRole struct {
	ID          int64
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	IsDeleted   bool
}

type DcTablesTableRole struct {
	ID           int64
	TableCatID   int64
	TableRolesID int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
	IsDeleted    bool
}

type DcUserDomainRole struct {
	ID            int64
	UserID        int64
	DomainRolesID int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	IsDeleted     bool
}

type DcUserTableRole struct {
	ID           int64
	UserID       int64
	TableRolesID int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
	IsDeleted    bool
}
