// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package user_domain_roles

import (
	"context"
)

const createDomainRole = `-- name: CreateDomainRole :one
INSERT INTO dc.domain_roles
("name", description, created_at, updated_at, is_deleted)
VALUES($1, $2, now(), now(), false)
RETURNING id, name, description, created_at, updated_at, is_deleted
`

type CreateDomainRoleParams struct {
	Name        string
	Description string
}

func (q *Queries) CreateDomainRole(ctx context.Context, arg CreateDomainRoleParams) (DcDomainRole, error) {
	row := q.db.QueryRowContext(ctx, createDomainRole, arg.Name, arg.Description)
	var i DcDomainRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const createDomainsDomainRole = `-- name: CreateDomainsDomainRole :one
INSERT INTO dc.domains_domain_roles
(domain_cat_id, domain_roles_id, created_at, updated_at, is_deleted)
VALUES($1, $2, now(), now(), false)
RETURNING id, domain_cat_id, domain_roles_id, created_at, updated_at, is_deleted
`

type CreateDomainsDomainRoleParams struct {
	DomainCatID   int64
	DomainRolesID int64
}

func (q *Queries) CreateDomainsDomainRole(ctx context.Context, arg CreateDomainsDomainRoleParams) (DcDomainsDomainRole, error) {
	row := q.db.QueryRowContext(ctx, createDomainsDomainRole, arg.DomainCatID, arg.DomainRolesID)
	var i DcDomainsDomainRole
	err := row.Scan(
		&i.ID,
		&i.DomainCatID,
		&i.DomainRolesID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const createTableRole = `-- name: CreateTableRole :one
INSERT INTO dc.table_roles
("name", description, created_at, updated_at, is_deleted)
VALUES($1, $2, now(), now(), false)
RETURNING id, name, description, created_at, updated_at, is_deleted
`

type CreateTableRoleParams struct {
	Name        string
	Description string
}

func (q *Queries) CreateTableRole(ctx context.Context, arg CreateTableRoleParams) (DcTableRole, error) {
	row := q.db.QueryRowContext(ctx, createTableRole, arg.Name, arg.Description)
	var i DcTableRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const createTablesTableRole = `-- name: CreateTablesTableRole :one
INSERT INTO dc.tables_table_roles
(table_cat_id, table_roles_id, created_at, updated_at, is_deleted)
VALUES($1, $2, now(), now(), false)
RETURNING id, table_cat_id, table_roles_id, created_at, updated_at, is_deleted
`

type CreateTablesTableRoleParams struct {
	TableCatID   int64
	TableRolesID int64
}

func (q *Queries) CreateTablesTableRole(ctx context.Context, arg CreateTablesTableRoleParams) (DcTablesTableRole, error) {
	row := q.db.QueryRowContext(ctx, createTablesTableRole, arg.TableCatID, arg.TableRolesID)
	var i DcTablesTableRole
	err := row.Scan(
		&i.ID,
		&i.TableCatID,
		&i.TableRolesID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const createUserDomainRole = `-- name: CreateUserDomainRole :one
INSERT INTO dc.user_domain_roles
(user_id, domain_roles_id, created_at, updated_at, is_deleted)
VALUES($1, $2, now(), now(), false)
RETURNING id, user_id, domain_roles_id, created_at, updated_at, is_deleted
`

type CreateUserDomainRoleParams struct {
	UserID        int64
	DomainRolesID int64
}

func (q *Queries) CreateUserDomainRole(ctx context.Context, arg CreateUserDomainRoleParams) (DcUserDomainRole, error) {
	row := q.db.QueryRowContext(ctx, createUserDomainRole, arg.UserID, arg.DomainRolesID)
	var i DcUserDomainRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DomainRolesID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const createUserTableRole = `-- name: CreateUserTableRole :one
INSERT INTO dc.user_table_roles
(user_id, table_roles_id, created_at, updated_at, is_deleted)
VALUES($1, $2, now(), now(), false)
RETURNING id, user_id, table_roles_id, created_at, updated_at, is_deleted
`

type CreateUserTableRoleParams struct {
	UserID       int64
	TableRolesID int64
}

func (q *Queries) CreateUserTableRole(ctx context.Context, arg CreateUserTableRoleParams) (DcUserTableRole, error) {
	row := q.db.QueryRowContext(ctx, createUserTableRole, arg.UserID, arg.TableRolesID)
	var i DcUserTableRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TableRolesID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const deleteDomainRoleById = `-- name: DeleteDomainRoleById :exec
UPDATE dc.domain_roles
SET is_deleted=true, updated_at=now()
WHERE id=$1
`

func (q *Queries) DeleteDomainRoleById(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDomainRoleById, id)
	return err
}

const deleteDomainsDomainRoleById = `-- name: DeleteDomainsDomainRoleById :exec
UPDATE dc.domains_domain_roles
SET is_deleted=true, updated_at=now()
WHERE id=$1
`

func (q *Queries) DeleteDomainsDomainRoleById(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDomainsDomainRoleById, id)
	return err
}

const deleteTableRoleById = `-- name: DeleteTableRoleById :exec
UPDATE dc.table_roles
SET is_deleted=true, updated_at=now()
WHERE id=$1
`

func (q *Queries) DeleteTableRoleById(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTableRoleById, id)
	return err
}

const deleteTablesTableRoleById = `-- name: DeleteTablesTableRoleById :exec
UPDATE dc.tables_table_roles
SET is_deleted=true, updated_at=now()
WHERE id=$1
`

func (q *Queries) DeleteTablesTableRoleById(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTablesTableRoleById, id)
	return err
}

const deleteUserDomainRoleById = `-- name: DeleteUserDomainRoleById :exec
UPDATE dc.user_domain_roles
SET is_deleted=true, updated_at=now()
WHERE id=$1
`

func (q *Queries) DeleteUserDomainRoleById(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserDomainRoleById, id)
	return err
}

const deleteUserTableRoleById = `-- name: DeleteUserTableRoleById :exec
UPDATE dc.user_table_roles
SET is_deleted=true, updated_at=now()
WHERE id=$1
`

func (q *Queries) DeleteUserTableRoleById(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserTableRoleById, id)
	return err
}

const getDeletedDomainRoleById = `-- name: GetDeletedDomainRoleById :one
SELECT id, name, description, created_at, updated_at, is_deleted
FROM dc.domain_roles
WHERE id = $1
AND is_deleted = true
`

func (q *Queries) GetDeletedDomainRoleById(ctx context.Context, id int64) (DcDomainRole, error) {
	row := q.db.QueryRowContext(ctx, getDeletedDomainRoleById, id)
	var i DcDomainRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getDeletedDomainRoles = `-- name: GetDeletedDomainRoles :many
SELECT id, name, description, created_at, updated_at, is_deleted
FROM dc.domain_roles
WHERE is_deleted = true
ORDER BY id
`

func (q *Queries) GetDeletedDomainRoles(ctx context.Context) ([]DcDomainRole, error) {
	rows, err := q.db.QueryContext(ctx, getDeletedDomainRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DcDomainRole
	for rows.Next() {
		var i DcDomainRole
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeletedDomainsDomainRoleById = `-- name: GetDeletedDomainsDomainRoleById :one
SELECT id, domain_cat_id, domain_roles_id, created_at, updated_at, is_deleted
FROM dc.domains_domain_roles
WHERE id = $1
AND is_deleted = true
`

func (q *Queries) GetDeletedDomainsDomainRoleById(ctx context.Context, id int64) (DcDomainsDomainRole, error) {
	row := q.db.QueryRowContext(ctx, getDeletedDomainsDomainRoleById, id)
	var i DcDomainsDomainRole
	err := row.Scan(
		&i.ID,
		&i.DomainCatID,
		&i.DomainRolesID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getDeletedDomainsDomainRoles = `-- name: GetDeletedDomainsDomainRoles :many
SELECT id, domain_cat_id, domain_roles_id, created_at, updated_at, is_deleted
FROM dc.domains_domain_roles
WHERE is_deleted = true
ORDER BY id
`

func (q *Queries) GetDeletedDomainsDomainRoles(ctx context.Context) ([]DcDomainsDomainRole, error) {
	rows, err := q.db.QueryContext(ctx, getDeletedDomainsDomainRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DcDomainsDomainRole
	for rows.Next() {
		var i DcDomainsDomainRole
		if err := rows.Scan(
			&i.ID,
			&i.DomainCatID,
			&i.DomainRolesID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeletedTableRoleById = `-- name: GetDeletedTableRoleById :one
SELECT id, name, description, created_at, updated_at, is_deleted
FROM dc.table_roles
WHERE id = $1
AND is_deleted = true
`

func (q *Queries) GetDeletedTableRoleById(ctx context.Context, id int64) (DcTableRole, error) {
	row := q.db.QueryRowContext(ctx, getDeletedTableRoleById, id)
	var i DcTableRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getDeletedTableRoles = `-- name: GetDeletedTableRoles :many
SELECT id, name, description, created_at, updated_at, is_deleted
FROM dc.table_roles
WHERE is_deleted = true
ORDER BY id
`

func (q *Queries) GetDeletedTableRoles(ctx context.Context) ([]DcTableRole, error) {
	rows, err := q.db.QueryContext(ctx, getDeletedTableRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DcTableRole
	for rows.Next() {
		var i DcTableRole
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeletedTablesTableRoleById = `-- name: GetDeletedTablesTableRoleById :one
SELECT id, table_cat_id, table_roles_id, created_at, updated_at, is_deleted
FROM dc.tables_table_roles
WHERE id = $1
AND is_deleted = true
`

func (q *Queries) GetDeletedTablesTableRoleById(ctx context.Context, id int64) (DcTablesTableRole, error) {
	row := q.db.QueryRowContext(ctx, getDeletedTablesTableRoleById, id)
	var i DcTablesTableRole
	err := row.Scan(
		&i.ID,
		&i.TableCatID,
		&i.TableRolesID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getDeletedTablesTableRoles = `-- name: GetDeletedTablesTableRoles :many
SELECT id, table_cat_id, table_roles_id, created_at, updated_at, is_deleted
FROM dc.tables_table_roles
WHERE is_deleted = true
ORDER BY id
`

func (q *Queries) GetDeletedTablesTableRoles(ctx context.Context) ([]DcTablesTableRole, error) {
	rows, err := q.db.QueryContext(ctx, getDeletedTablesTableRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DcTablesTableRole
	for rows.Next() {
		var i DcTablesTableRole
		if err := rows.Scan(
			&i.ID,
			&i.TableCatID,
			&i.TableRolesID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeletedUserDomainRoleById = `-- name: GetDeletedUserDomainRoleById :one
SELECT id, user_id, domain_roles_id, created_at, updated_at, is_deleted
FROM dc.user_domain_roles
WHERE id = $1
AND is_deleted = true
`

func (q *Queries) GetDeletedUserDomainRoleById(ctx context.Context, id int64) (DcUserDomainRole, error) {
	row := q.db.QueryRowContext(ctx, getDeletedUserDomainRoleById, id)
	var i DcUserDomainRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DomainRolesID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getDeletedUserDomainRoles = `-- name: GetDeletedUserDomainRoles :many
SELECT id, user_id, domain_roles_id, created_at, updated_at, is_deleted
FROM dc.user_domain_roles
WHERE is_deleted = true
ORDER BY id
`

func (q *Queries) GetDeletedUserDomainRoles(ctx context.Context) ([]DcUserDomainRole, error) {
	rows, err := q.db.QueryContext(ctx, getDeletedUserDomainRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DcUserDomainRole
	for rows.Next() {
		var i DcUserDomainRole
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DomainRolesID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeletedUserTableRoleById = `-- name: GetDeletedUserTableRoleById :one
SELECT id, user_id, table_roles_id, created_at, updated_at, is_deleted
FROM dc.user_table_roles
WHERE id = $1
AND is_deleted = true
`

func (q *Queries) GetDeletedUserTableRoleById(ctx context.Context, id int64) (DcUserTableRole, error) {
	row := q.db.QueryRowContext(ctx, getDeletedUserTableRoleById, id)
	var i DcUserTableRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TableRolesID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getDeletedUserTableRoles = `-- name: GetDeletedUserTableRoles :many
SELECT id, user_id, table_roles_id, created_at, updated_at, is_deleted
FROM dc.user_table_roles
WHERE is_deleted = true
ORDER BY id
`

func (q *Queries) GetDeletedUserTableRoles(ctx context.Context) ([]DcUserTableRole, error) {
	rows, err := q.db.QueryContext(ctx, getDeletedUserTableRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DcUserTableRole
	for rows.Next() {
		var i DcUserTableRole
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TableRolesID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDomainRoleById = `-- name: GetDomainRoleById :one

SELECT id, name, description, created_at, updated_at, is_deleted
FROM dc.domain_roles
WHERE id = $1
AND is_deleted = false
`

// =========================================================
// dc.domain_roles
// =========================================================
func (q *Queries) GetDomainRoleById(ctx context.Context, id int64) (DcDomainRole, error) {
	row := q.db.QueryRowContext(ctx, getDomainRoleById, id)
	var i DcDomainRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getDomainRoles = `-- name: GetDomainRoles :many
SELECT id, name, description, created_at, updated_at, is_deleted
FROM dc.domain_roles
WHERE is_deleted = false
ORDER BY id
`

func (q *Queries) GetDomainRoles(ctx context.Context) ([]DcDomainRole, error) {
	rows, err := q.db.QueryContext(ctx, getDomainRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DcDomainRole
	for rows.Next() {
		var i DcDomainRole
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDomainsDomainRoleById = `-- name: GetDomainsDomainRoleById :one

SELECT id, domain_cat_id, domain_roles_id, created_at, updated_at, is_deleted
FROM dc.domains_domain_roles
WHERE id = $1
AND is_deleted = false
`

// =========================================================
// dc.domains_domain_roles
// =========================================================
func (q *Queries) GetDomainsDomainRoleById(ctx context.Context, id int64) (DcDomainsDomainRole, error) {
	row := q.db.QueryRowContext(ctx, getDomainsDomainRoleById, id)
	var i DcDomainsDomainRole
	err := row.Scan(
		&i.ID,
		&i.DomainCatID,
		&i.DomainRolesID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getDomainsDomainRoles = `-- name: GetDomainsDomainRoles :many
SELECT id, domain_cat_id, domain_roles_id, created_at, updated_at, is_deleted
FROM dc.domains_domain_roles
WHERE is_deleted = false
ORDER BY id
`

func (q *Queries) GetDomainsDomainRoles(ctx context.Context) ([]DcDomainsDomainRole, error) {
	rows, err := q.db.QueryContext(ctx, getDomainsDomainRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DcDomainsDomainRole
	for rows.Next() {
		var i DcDomainsDomainRole
		if err := rows.Scan(
			&i.ID,
			&i.DomainCatID,
			&i.DomainRolesID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTableRoleById = `-- name: GetTableRoleById :one

SELECT id, name, description, created_at, updated_at, is_deleted
FROM dc.table_roles
WHERE id = $1
AND is_deleted = false
`

// =========================================================
// dc.table_roles
// =========================================================
func (q *Queries) GetTableRoleById(ctx context.Context, id int64) (DcTableRole, error) {
	row := q.db.QueryRowContext(ctx, getTableRoleById, id)
	var i DcTableRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getTableRoles = `-- name: GetTableRoles :many
SELECT id, name, description, created_at, updated_at, is_deleted
FROM dc.table_roles
WHERE is_deleted = false
ORDER BY id
`

func (q *Queries) GetTableRoles(ctx context.Context) ([]DcTableRole, error) {
	rows, err := q.db.QueryContext(ctx, getTableRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DcTableRole
	for rows.Next() {
		var i DcTableRole
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTablesTableRoleById = `-- name: GetTablesTableRoleById :one

SELECT id, table_cat_id, table_roles_id, created_at, updated_at, is_deleted
FROM dc.tables_table_roles
WHERE id = $1
AND is_deleted = false
`

// =========================================================
// dc.tables_table_roles
// =========================================================
func (q *Queries) GetTablesTableRoleById(ctx context.Context, id int64) (DcTablesTableRole, error) {
	row := q.db.QueryRowContext(ctx, getTablesTableRoleById, id)
	var i DcTablesTableRole
	err := row.Scan(
		&i.ID,
		&i.TableCatID,
		&i.TableRolesID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getTablesTableRoles = `-- name: GetTablesTableRoles :many
SELECT id, table_cat_id, table_roles_id, created_at, updated_at, is_deleted
FROM dc.tables_table_roles
WHERE is_deleted = false
ORDER BY id
`

func (q *Queries) GetTablesTableRoles(ctx context.Context) ([]DcTablesTableRole, error) {
	rows, err := q.db.QueryContext(ctx, getTablesTableRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DcTablesTableRole
	for rows.Next() {
		var i DcTablesTableRole
		if err := rows.Scan(
			&i.ID,
			&i.TableCatID,
			&i.TableRolesID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserDomainRoleById = `-- name: GetUserDomainRoleById :one

SELECT id, user_id, domain_roles_id, created_at, updated_at, is_deleted
FROM dc.user_domain_roles
WHERE id = $1
AND is_deleted = false
`

// =========================================================
// dc.user_domain_roles
// =========================================================
func (q *Queries) GetUserDomainRoleById(ctx context.Context, id int64) (DcUserDomainRole, error) {
	row := q.db.QueryRowContext(ctx, getUserDomainRoleById, id)
	var i DcUserDomainRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DomainRolesID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getUserDomainRoles = `-- name: GetUserDomainRoles :many
SELECT id, user_id, domain_roles_id, created_at, updated_at, is_deleted
FROM dc.user_domain_roles
WHERE is_deleted = false
ORDER BY id
`

func (q *Queries) GetUserDomainRoles(ctx context.Context) ([]DcUserDomainRole, error) {
	rows, err := q.db.QueryContext(ctx, getUserDomainRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DcUserDomainRole
	for rows.Next() {
		var i DcUserDomainRole
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DomainRolesID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTableRoleById = `-- name: GetUserTableRoleById :one

SELECT id, user_id, table_roles_id, created_at, updated_at, is_deleted
FROM dc.user_table_roles
WHERE id = $1
AND is_deleted = false
`

// =========================================================
// dc.user_table_roles
// =========================================================
func (q *Queries) GetUserTableRoleById(ctx context.Context, id int64) (DcUserTableRole, error) {
	row := q.db.QueryRowContext(ctx, getUserTableRoleById, id)
	var i DcUserTableRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TableRolesID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getUserTableRoles = `-- name: GetUserTableRoles :many
SELECT id, user_id, table_roles_id, created_at, updated_at, is_deleted
FROM dc.user_table_roles
WHERE is_deleted = false
ORDER BY id
`

func (q *Queries) GetUserTableRoles(ctx context.Context) ([]DcUserTableRole, error) {
	rows, err := q.db.QueryContext(ctx, getUserTableRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DcUserTableRole
	for rows.Next() {
		var i DcUserTableRole
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TableRolesID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const undeleteDomainRoleById = `-- name: UndeleteDomainRoleById :exec
UPDATE dc.domain_roles
SET is_deleted=false, updated_at=now()
WHERE id=$1
`

func (q *Queries) UndeleteDomainRoleById(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, undeleteDomainRoleById, id)
	return err
}

const undeleteDomainsDomainRoleById = `-- name: UndeleteDomainsDomainRoleById :exec
UPDATE dc.domains_domain_roles
SET is_deleted=false, updated_at=now()
WHERE id=$1
`

func (q *Queries) UndeleteDomainsDomainRoleById(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, undeleteDomainsDomainRoleById, id)
	return err
}

const undeleteTableRoleById = `-- name: UndeleteTableRoleById :exec
UPDATE dc.table_roles
SET is_deleted=false, updated_at=now()
WHERE id=$1
`

func (q *Queries) UndeleteTableRoleById(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, undeleteTableRoleById, id)
	return err
}

const undeleteTablesTableRoleById = `-- name: UndeleteTablesTableRoleById :exec
UPDATE dc.tables_table_roles
SET is_deleted=false, updated_at=now()
WHERE id=$1
`

func (q *Queries) UndeleteTablesTableRoleById(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, undeleteTablesTableRoleById, id)
	return err
}

const undeleteUserDomainRoleById = `-- name: UndeleteUserDomainRoleById :exec
UPDATE dc.user_domain_roles
SET is_deleted=false, updated_at=now()
WHERE id=$1
`

func (q *Queries) UndeleteUserDomainRoleById(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, undeleteUserDomainRoleById, id)
	return err
}

const undeleteUserTableRoleById = `-- name: UndeleteUserTableRoleById :exec
UPDATE dc.user_table_roles
SET is_deleted=false, updated_at=now()
WHERE id=$1
`

func (q *Queries) UndeleteUserTableRoleById(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, undeleteUserTableRoleById, id)
	return err
}

const updateDomainRoleById = `-- name: UpdateDomainRoleById :one
UPDATE dc.domain_roles
SET "name"=$2, description=$3, updated_at=now()
WHERE id=$1
AND is_deleted = false
RETURNING id, name, description, created_at, updated_at, is_deleted
`

type UpdateDomainRoleByIdParams struct {
	ID          int64
	Name        string
	Description string
}

func (q *Queries) UpdateDomainRoleById(ctx context.Context, arg UpdateDomainRoleByIdParams) (DcDomainRole, error) {
	row := q.db.QueryRowContext(ctx, updateDomainRoleById, arg.ID, arg.Name, arg.Description)
	var i DcDomainRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const updateDomainsDomainRoleById = `-- name: UpdateDomainsDomainRoleById :one
UPDATE dc.domains_domain_roles
SET domain_cat_id=$2, domain_roles_id=$3, updated_at=now()
WHERE id=$1
AND is_deleted = false
RETURNING id, domain_cat_id, domain_roles_id, created_at, updated_at, is_deleted
`

type UpdateDomainsDomainRoleByIdParams struct {
	ID            int64
	DomainCatID   int64
	DomainRolesID int64
}

func (q *Queries) UpdateDomainsDomainRoleById(ctx context.Context, arg UpdateDomainsDomainRoleByIdParams) (DcDomainsDomainRole, error) {
	row := q.db.QueryRowContext(ctx, updateDomainsDomainRoleById, arg.ID, arg.DomainCatID, arg.DomainRolesID)
	var i DcDomainsDomainRole
	err := row.Scan(
		&i.ID,
		&i.DomainCatID,
		&i.DomainRolesID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const updateTableRoleById = `-- name: UpdateTableRoleById :one
UPDATE dc.table_roles
SET "name"=$2, description=$3, updated_at=now()
WHERE id=$1
AND is_deleted = false
RETURNING id, name, description, created_at, updated_at, is_deleted
`

type UpdateTableRoleByIdParams struct {
	ID          int64
	Name        string
	Description string
}

func (q *Queries) UpdateTableRoleById(ctx context.Context, arg UpdateTableRoleByIdParams) (DcTableRole, error) {
	row := q.db.QueryRowContext(ctx, updateTableRoleById, arg.ID, arg.Name, arg.Description)
	var i DcTableRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const updateTablesTableRoleById = `-- name: UpdateTablesTableRoleById :one
UPDATE dc.tables_table_roles
SET table_cat_id=$2, table_roles_id=$3, updated_at=now()
WHERE id=$1
AND is_deleted = false
RETURNING id, table_cat_id, table_roles_id, created_at, updated_at, is_deleted
`

type UpdateTablesTableRoleByIdParams struct {
	ID           int64
	TableCatID   int64
	TableRolesID int64
}

func (q *Queries) UpdateTablesTableRoleById(ctx context.Context, arg UpdateTablesTableRoleByIdParams) (DcTablesTableRole, error) {
	row := q.db.QueryRowContext(ctx, updateTablesTableRoleById, arg.ID, arg.TableCatID, arg.TableRolesID)
	var i DcTablesTableRole
	err := row.Scan(
		&i.ID,
		&i.TableCatID,
		&i.TableRolesID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const updateUserDomainRoleById = `-- name: UpdateUserDomainRoleById :one
UPDATE dc.user_domain_roles
SET user_id=$2, domain_roles_id=$3, updated_at=now()
WHERE id=$1
AND is_deleted = false
RETURNING id, user_id, domain_roles_id, created_at, updated_at, is_deleted
`

type UpdateUserDomainRoleByIdParams struct {
	ID            int64
	UserID        int64
	DomainRolesID int64
}

func (q *Queries) UpdateUserDomainRoleById(ctx context.Context, arg UpdateUserDomainRoleByIdParams) (DcUserDomainRole, error) {
	row := q.db.QueryRowContext(ctx, updateUserDomainRoleById, arg.ID, arg.UserID, arg.DomainRolesID)
	var i DcUserDomainRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DomainRolesID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const updateUserTableRoleById = `-- name: UpdateUserTableRoleById :one
UPDATE dc.user_table_roles
SET user_id=$2, table_roles_id=$3, updated_at=now()
WHERE id=$1
AND is_deleted = false
RETURNING id, user_id, table_roles_id, created_at, updated_at, is_deleted
`

type UpdateUserTableRoleByIdParams struct {
	ID           int64
	UserID       int64
	TableRolesID int64
}

func (q *Queries) UpdateUserTableRoleById(ctx context.Context, arg UpdateUserTableRoleByIdParams) (DcUserTableRole, error) {
	row := q.db.QueryRowContext(ctx, updateUserTableRoleById, arg.ID, arg.UserID, arg.TableRolesID)
	var i DcUserTableRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TableRolesID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}
