// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: user_domain_roles/v1/user_domain_roles.proto

package userdomainrolesv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserDomainRolesService_GetDomainRoleById_FullMethodName            = "/user_domain_roles.v1.UserDomainRolesService/GetDomainRoleById"
	UserDomainRolesService_GetDomainRoles_FullMethodName               = "/user_domain_roles.v1.UserDomainRolesService/GetDomainRoles"
	UserDomainRolesService_GetDeletedDomainRoleById_FullMethodName     = "/user_domain_roles.v1.UserDomainRolesService/GetDeletedDomainRoleById"
	UserDomainRolesService_GetDeletedDomainRoles_FullMethodName        = "/user_domain_roles.v1.UserDomainRolesService/GetDeletedDomainRoles"
	UserDomainRolesService_CreateDomainRole_FullMethodName             = "/user_domain_roles.v1.UserDomainRolesService/CreateDomainRole"
	UserDomainRolesService_UpdateDomainRoleById_FullMethodName         = "/user_domain_roles.v1.UserDomainRolesService/UpdateDomainRoleById"
	UserDomainRolesService_DeleteDomainRoleById_FullMethodName         = "/user_domain_roles.v1.UserDomainRolesService/DeleteDomainRoleById"
	UserDomainRolesService_UndeleteDomainRoleById_FullMethodName       = "/user_domain_roles.v1.UserDomainRolesService/UndeleteDomainRoleById"
	UserDomainRolesService_GetTableRoleById_FullMethodName             = "/user_domain_roles.v1.UserDomainRolesService/GetTableRoleById"
	UserDomainRolesService_GetTableRoles_FullMethodName                = "/user_domain_roles.v1.UserDomainRolesService/GetTableRoles"
	UserDomainRolesService_GetDeletedTableRoleById_FullMethodName      = "/user_domain_roles.v1.UserDomainRolesService/GetDeletedTableRoleById"
	UserDomainRolesService_GetDeletedTableRoles_FullMethodName         = "/user_domain_roles.v1.UserDomainRolesService/GetDeletedTableRoles"
	UserDomainRolesService_CreateTableRole_FullMethodName              = "/user_domain_roles.v1.UserDomainRolesService/CreateTableRole"
	UserDomainRolesService_UpdateTableRoleById_FullMethodName          = "/user_domain_roles.v1.UserDomainRolesService/UpdateTableRoleById"
	UserDomainRolesService_DeleteTableRoleById_FullMethodName          = "/user_domain_roles.v1.UserDomainRolesService/DeleteTableRoleById"
	UserDomainRolesService_UndeleteTableRoleById_FullMethodName        = "/user_domain_roles.v1.UserDomainRolesService/UndeleteTableRoleById"
	UserDomainRolesService_GetUserDomainRoleById_FullMethodName        = "/user_domain_roles.v1.UserDomainRolesService/GetUserDomainRoleById"
	UserDomainRolesService_GetUserDomainRoles_FullMethodName           = "/user_domain_roles.v1.UserDomainRolesService/GetUserDomainRoles"
	UserDomainRolesService_GetDeletedUserDomainRoleById_FullMethodName = "/user_domain_roles.v1.UserDomainRolesService/GetDeletedUserDomainRoleById"
	UserDomainRolesService_GetDeletedUserDomainRoles_FullMethodName    = "/user_domain_roles.v1.UserDomainRolesService/GetDeletedUserDomainRoles"
	UserDomainRolesService_CreateUserDomainRole_FullMethodName         = "/user_domain_roles.v1.UserDomainRolesService/CreateUserDomainRole"
	UserDomainRolesService_UpdateUserDomainRoleById_FullMethodName     = "/user_domain_roles.v1.UserDomainRolesService/UpdateUserDomainRoleById"
	UserDomainRolesService_DeleteUserDomainRoleById_FullMethodName     = "/user_domain_roles.v1.UserDomainRolesService/DeleteUserDomainRoleById"
	UserDomainRolesService_UndeleteUserDomainRoleById_FullMethodName   = "/user_domain_roles.v1.UserDomainRolesService/UndeleteUserDomainRoleById"
	UserDomainRolesService_GetUserTableRoleById_FullMethodName         = "/user_domain_roles.v1.UserDomainRolesService/GetUserTableRoleById"
	UserDomainRolesService_GetUserTableRoles_FullMethodName            = "/user_domain_roles.v1.UserDomainRolesService/GetUserTableRoles"
	UserDomainRolesService_GetDeletedUserTableRoleById_FullMethodName  = "/user_domain_roles.v1.UserDomainRolesService/GetDeletedUserTableRoleById"
	UserDomainRolesService_GetDeletedUserTableRoles_FullMethodName     = "/user_domain_roles.v1.UserDomainRolesService/GetDeletedUserTableRoles"
	UserDomainRolesService_CreateUserTableRole_FullMethodName          = "/user_domain_roles.v1.UserDomainRolesService/CreateUserTableRole"
	UserDomainRolesService_UpdateUserTableRoleById_FullMethodName      = "/user_domain_roles.v1.UserDomainRolesService/UpdateUserTableRoleById"
	UserDomainRolesService_DeleteUserTableRoleById_FullMethodName      = "/user_domain_roles.v1.UserDomainRolesService/DeleteUserTableRoleById"
	UserDomainRolesService_UndeleteUserTableRoleById_FullMethodName    = "/user_domain_roles.v1.UserDomainRolesService/UndeleteUserTableRoleById"
)

// UserDomainRolesServiceClient is the client API for UserDomainRolesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UserDomainRolesService mirrors query.sql one-to-one:
// 8 standard CRUD calls per table.
type UserDomainRolesServiceClient interface {
	// dc.domain_roles
	GetDomainRoleById(ctx context.Context, in *GetDomainRoleByIdRequest, opts ...grpc.CallOption) (*GetDomainRoleByIdResponse, error)
	GetDomainRoles(ctx context.Context, in *GetDomainRolesRequest, opts ...grpc.CallOption) (*GetDomainRolesResponse, error)
	GetDeletedDomainRoleById(ctx context.Context, in *GetDeletedDomainRoleByIdRequest, opts ...grpc.CallOption) (*GetDeletedDomainRoleByIdResponse, error)
	GetDeletedDomainRoles(ctx context.Context, in *GetDeletedDomainRolesRequest, opts ...grpc.CallOption) (*GetDeletedDomainRolesResponse, error)
	CreateDomainRole(ctx context.Context, in *CreateDomainRoleRequest, opts ...grpc.CallOption) (*CreateDomainRoleResponse, error)
	UpdateDomainRoleById(ctx context.Context, in *UpdateDomainRoleByIdRequest, opts ...grpc.CallOption) (*UpdateDomainRoleByIdResponse, error)
	DeleteDomainRoleById(ctx context.Context, in *DeleteDomainRoleByIdRequest, opts ...grpc.CallOption) (*DeleteDomainRoleByIdResponse, error)
	UndeleteDomainRoleById(ctx context.Context, in *UndeleteDomainRoleByIdRequest, opts ...grpc.CallOption) (*UndeleteDomainRoleByIdResponse, error)
	// dc.table_roles
	GetTableRoleById(ctx context.Context, in *GetTableRoleByIdRequest, opts ...grpc.CallOption) (*GetTableRoleByIdResponse, error)
	GetTableRoles(ctx context.Context, in *GetTableRolesRequest, opts ...grpc.CallOption) (*GetTableRolesResponse, error)
	GetDeletedTableRoleById(ctx context.Context, in *GetDeletedTableRoleByIdRequest, opts ...grpc.CallOption) (*GetDeletedTableRoleByIdResponse, error)
	GetDeletedTableRoles(ctx context.Context, in *GetDeletedTableRolesRequest, opts ...grpc.CallOption) (*GetDeletedTableRolesResponse, error)
	CreateTableRole(ctx context.Context, in *CreateTableRoleRequest, opts ...grpc.CallOption) (*CreateTableRoleResponse, error)
	UpdateTableRoleById(ctx context.Context, in *UpdateTableRoleByIdRequest, opts ...grpc.CallOption) (*UpdateTableRoleByIdResponse, error)
	DeleteTableRoleById(ctx context.Context, in *DeleteTableRoleByIdRequest, opts ...grpc.CallOption) (*DeleteTableRoleByIdResponse, error)
	UndeleteTableRoleById(ctx context.Context, in *UndeleteTableRoleByIdRequest, opts ...grpc.CallOption) (*UndeleteTableRoleByIdResponse, error)
	// dc.user_domain_roles
	GetUserDomainRoleById(ctx context.Context, in *GetUserDomainRoleByIdRequest, opts ...grpc.CallOption) (*GetUserDomainRoleByIdResponse, error)
	GetUserDomainRoles(ctx context.Context, in *GetUserDomainRolesRequest, opts ...grpc.CallOption) (*GetUserDomainRolesResponse, error)
	GetDeletedUserDomainRoleById(ctx context.Context, in *GetDeletedUserDomainRoleByIdRequest, opts ...grpc.CallOption) (*GetDeletedUserDomainRoleByIdResponse, error)
	GetDeletedUserDomainRoles(ctx context.Context, in *GetDeletedUserDomainRolesRequest, opts ...grpc.CallOption) (*GetDeletedUserDomainRolesResponse, error)
	CreateUserDomainRole(ctx context.Context, in *CreateUserDomainRoleRequest, opts ...grpc.CallOption) (*CreateUserDomainRoleResponse, error)
	UpdateUserDomainRoleById(ctx context.Context, in *UpdateUserDomainRoleByIdRequest, opts ...grpc.CallOption) (*UpdateUserDomainRoleByIdResponse, error)
	DeleteUserDomainRoleById(ctx context.Context, in *DeleteUserDomainRoleByIdRequest, opts ...grpc.CallOption) (*DeleteUserDomainRoleByIdResponse, error)
	UndeleteUserDomainRoleById(ctx context.Context, in *UndeleteUserDomainRoleByIdRequest, opts ...grpc.CallOption) (*UndeleteUserDomainRoleByIdResponse, error)
	// dc.user_table_roles
	GetUserTableRoleById(ctx context.Context, in *GetUserTableRoleByIdRequest, opts ...grpc.CallOption) (*GetUserTableRoleByIdResponse, error)
	GetUserTableRoles(ctx context.Context, in *GetUserTableRolesRequest, opts ...grpc.CallOption) (*GetUserTableRolesResponse, error)
	GetDeletedUserTableRoleById(ctx context.Context, in *GetDeletedUserTableRoleByIdRequest, opts ...grpc.CallOption) (*GetDeletedUserTableRoleByIdResponse, error)
	GetDeletedUserTableRoles(ctx context.Context, in *GetDeletedUserTableRolesRequest, opts ...grpc.CallOption) (*GetDeletedUserTableRolesResponse, error)
	CreateUserTableRole(ctx context.Context, in *CreateUserTableRoleRequest, opts ...grpc.CallOption) (*CreateUserTableRoleResponse, error)
	UpdateUserTableRoleById(ctx context.Context, in *UpdateUserTableRoleByIdRequest, opts ...grpc.CallOption) (*UpdateUserTableRoleByIdResponse, error)
	DeleteUserTableRoleById(ctx context.Context, in *DeleteUserTableRoleByIdRequest, opts ...grpc.CallOption) (*DeleteUserTableRoleByIdResponse, error)
	UndeleteUserTableRoleById(ctx context.Context, in *UndeleteUserTableRoleByIdRequest, opts ...grpc.CallOption) (*UndeleteUserTableRoleByIdResponse, error)
}

type userDomainRolesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserDomainRolesServiceClient(cc grpc.ClientConnInterface) UserDomainRolesServiceClient {
	return &userDomainRolesServiceClient{cc}
}

func (c *userDomainRolesServiceClient) GetDomainRoleById(ctx context.Context, in *GetDomainRoleByIdRequest, opts ...grpc.CallOption) (*GetDomainRoleByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDomainRoleByIdResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_GetDomainRoleById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) GetDomainRoles(ctx context.Context, in *GetDomainRolesRequest, opts ...grpc.CallOption) (*GetDomainRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDomainRolesResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_GetDomainRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) GetDeletedDomainRoleById(ctx context.Context, in *GetDeletedDomainRoleByIdRequest, opts ...grpc.CallOption) (*GetDeletedDomainRoleByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeletedDomainRoleByIdResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_GetDeletedDomainRoleById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) GetDeletedDomainRoles(ctx context.Context, in *GetDeletedDomainRolesRequest, opts ...grpc.CallOption) (*GetDeletedDomainRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeletedDomainRolesResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_GetDeletedDomainRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) CreateDomainRole(ctx context.Context, in *CreateDomainRoleRequest, opts ...grpc.CallOption) (*CreateDomainRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDomainRoleResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_CreateDomainRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) UpdateDomainRoleById(ctx context.Context, in *UpdateDomainRoleByIdRequest, opts ...grpc.CallOption) (*UpdateDomainRoleByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDomainRoleByIdResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_UpdateDomainRoleById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) DeleteDomainRoleById(ctx context.Context, in *DeleteDomainRoleByIdRequest, opts ...grpc.CallOption) (*DeleteDomainRoleByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDomainRoleByIdResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_DeleteDomainRoleById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) UndeleteDomainRoleById(ctx context.Context, in *UndeleteDomainRoleByIdRequest, opts ...grpc.CallOption) (*UndeleteDomainRoleByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UndeleteDomainRoleByIdResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_UndeleteDomainRoleById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) GetTableRoleById(ctx context.Context, in *GetTableRoleByIdRequest, opts ...grpc.CallOption) (*GetTableRoleByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTableRoleByIdResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_GetTableRoleById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) GetTableRoles(ctx context.Context, in *GetTableRolesRequest, opts ...grpc.CallOption) (*GetTableRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTableRolesResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_GetTableRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) GetDeletedTableRoleById(ctx context.Context, in *GetDeletedTableRoleByIdRequest, opts ...grpc.CallOption) (*GetDeletedTableRoleByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeletedTableRoleByIdResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_GetDeletedTableRoleById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) GetDeletedTableRoles(ctx context.Context, in *GetDeletedTableRolesRequest, opts ...grpc.CallOption) (*GetDeletedTableRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeletedTableRolesResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_GetDeletedTableRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) CreateTableRole(ctx context.Context, in *CreateTableRoleRequest, opts ...grpc.CallOption) (*CreateTableRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTableRoleResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_CreateTableRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) UpdateTableRoleById(ctx context.Context, in *UpdateTableRoleByIdRequest, opts ...grpc.CallOption) (*UpdateTableRoleByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTableRoleByIdResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_UpdateTableRoleById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) DeleteTableRoleById(ctx context.Context, in *DeleteTableRoleByIdRequest, opts ...grpc.CallOption) (*DeleteTableRoleByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTableRoleByIdResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_DeleteTableRoleById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) UndeleteTableRoleById(ctx context.Context, in *UndeleteTableRoleByIdRequest, opts ...grpc.CallOption) (*UndeleteTableRoleByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UndeleteTableRoleByIdResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_UndeleteTableRoleById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) GetUserDomainRoleById(ctx context.Context, in *GetUserDomainRoleByIdRequest, opts ...grpc.CallOption) (*GetUserDomainRoleByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserDomainRoleByIdResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_GetUserDomainRoleById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) GetUserDomainRoles(ctx context.Context, in *GetUserDomainRolesRequest, opts ...grpc.CallOption) (*GetUserDomainRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserDomainRolesResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_GetUserDomainRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) GetDeletedUserDomainRoleById(ctx context.Context, in *GetDeletedUserDomainRoleByIdRequest, opts ...grpc.CallOption) (*GetDeletedUserDomainRoleByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeletedUserDomainRoleByIdResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_GetDeletedUserDomainRoleById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) GetDeletedUserDomainRoles(ctx context.Context, in *GetDeletedUserDomainRolesRequest, opts ...grpc.CallOption) (*GetDeletedUserDomainRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeletedUserDomainRolesResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_GetDeletedUserDomainRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) CreateUserDomainRole(ctx context.Context, in *CreateUserDomainRoleRequest, opts ...grpc.CallOption) (*CreateUserDomainRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserDomainRoleResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_CreateUserDomainRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) UpdateUserDomainRoleById(ctx context.Context, in *UpdateUserDomainRoleByIdRequest, opts ...grpc.CallOption) (*UpdateUserDomainRoleByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserDomainRoleByIdResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_UpdateUserDomainRoleById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) DeleteUserDomainRoleById(ctx context.Context, in *DeleteUserDomainRoleByIdRequest, opts ...grpc.CallOption) (*DeleteUserDomainRoleByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserDomainRoleByIdResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_DeleteUserDomainRoleById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) UndeleteUserDomainRoleById(ctx context.Context, in *UndeleteUserDomainRoleByIdRequest, opts ...grpc.CallOption) (*UndeleteUserDomainRoleByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UndeleteUserDomainRoleByIdResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_UndeleteUserDomainRoleById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) GetUserTableRoleById(ctx context.Context, in *GetUserTableRoleByIdRequest, opts ...grpc.CallOption) (*GetUserTableRoleByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserTableRoleByIdResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_GetUserTableRoleById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) GetUserTableRoles(ctx context.Context, in *GetUserTableRolesRequest, opts ...grpc.CallOption) (*GetUserTableRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserTableRolesResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_GetUserTableRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) GetDeletedUserTableRoleById(ctx context.Context, in *GetDeletedUserTableRoleByIdRequest, opts ...grpc.CallOption) (*GetDeletedUserTableRoleByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeletedUserTableRoleByIdResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_GetDeletedUserTableRoleById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) GetDeletedUserTableRoles(ctx context.Context, in *GetDeletedUserTableRolesRequest, opts ...grpc.CallOption) (*GetDeletedUserTableRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeletedUserTableRolesResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_GetDeletedUserTableRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) CreateUserTableRole(ctx context.Context, in *CreateUserTableRoleRequest, opts ...grpc.CallOption) (*CreateUserTableRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserTableRoleResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_CreateUserTableRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) UpdateUserTableRoleById(ctx context.Context, in *UpdateUserTableRoleByIdRequest, opts ...grpc.CallOption) (*UpdateUserTableRoleByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserTableRoleByIdResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_UpdateUserTableRoleById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) DeleteUserTableRoleById(ctx context.Context, in *DeleteUserTableRoleByIdRequest, opts ...grpc.CallOption) (*DeleteUserTableRoleByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserTableRoleByIdResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_DeleteUserTableRoleById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDomainRolesServiceClient) UndeleteUserTableRoleById(ctx context.Context, in *UndeleteUserTableRoleByIdRequest, opts ...grpc.CallOption) (*UndeleteUserTableRoleByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UndeleteUserTableRoleByIdResponse)
	err := c.cc.Invoke(ctx, UserDomainRolesService_UndeleteUserTableRoleById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserDomainRolesServiceServer is the server API for UserDomainRolesService service.
// All implementations must embed UnimplementedUserDomainRolesServiceServer
// for forward compatibility.
//
// UserDomainRolesService mirrors query.sql one-to-one:
// 8 standard CRUD calls per table.
type UserDomainRolesServiceServer interface {
	// dc.domain_roles
	GetDomainRoleById(context.Context, *GetDomainRoleByIdRequest) (*GetDomainRoleByIdResponse, error)
	GetDomainRoles(context.Context, *GetDomainRolesRequest) (*GetDomainRolesResponse, error)
	GetDeletedDomainRoleById(context.Context, *GetDeletedDomainRoleByIdRequest) (*GetDeletedDomainRoleByIdResponse, error)
	GetDeletedDomainRoles(context.Context, *GetDeletedDomainRolesRequest) (*GetDeletedDomainRolesResponse, error)
	CreateDomainRole(context.Context, *CreateDomainRoleRequest) (*CreateDomainRoleResponse, error)
	UpdateDomainRoleById(context.Context, *UpdateDomainRoleByIdRequest) (*UpdateDomainRoleByIdResponse, error)
	DeleteDomainRoleById(context.Context, *DeleteDomainRoleByIdRequest) (*DeleteDomainRoleByIdResponse, error)
	UndeleteDomainRoleById(context.Context, *UndeleteDomainRoleByIdRequest) (*UndeleteDomainRoleByIdResponse, error)
	// dc.table_roles
	GetTableRoleById(context.Context, *GetTableRoleByIdRequest) (*GetTableRoleByIdResponse, error)
	GetTableRoles(context.Context, *GetTableRolesRequest) (*GetTableRolesResponse, error)
	GetDeletedTableRoleById(context.Context, *GetDeletedTableRoleByIdRequest) (*GetDeletedTableRoleByIdResponse, error)
	GetDeletedTableRoles(context.Context, *GetDeletedTableRolesRequest) (*GetDeletedTableRolesResponse, error)
	CreateTableRole(context.Context, *CreateTableRoleRequest) (*CreateTableRoleResponse, error)
	UpdateTableRoleById(context.Context, *UpdateTableRoleByIdRequest) (*UpdateTableRoleByIdResponse, error)
	DeleteTableRoleById(context.Context, *DeleteTableRoleByIdRequest) (*DeleteTableRoleByIdResponse, error)
	UndeleteTableRoleById(context.Context, *UndeleteTableRoleByIdRequest) (*UndeleteTableRoleByIdResponse, error)
	// dc.user_domain_roles
	GetUserDomainRoleById(context.Context, *GetUserDomainRoleByIdRequest) (*GetUserDomainRoleByIdResponse, error)
	GetUserDomainRoles(context.Context, *GetUserDomainRolesRequest) (*GetUserDomainRolesResponse, error)
	GetDeletedUserDomainRoleById(context.Context, *GetDeletedUserDomainRoleByIdRequest) (*GetDeletedUserDomainRoleByIdResponse, error)
	GetDeletedUserDomainRoles(context.Context, *GetDeletedUserDomainRolesRequest) (*GetDeletedUserDomainRolesResponse, error)
	CreateUserDomainRole(context.Context, *CreateUserDomainRoleRequest) (*CreateUserDomainRoleResponse, error)
	UpdateUserDomainRoleById(context.Context, *UpdateUserDomainRoleByIdRequest) (*UpdateUserDomainRoleByIdResponse, error)
	DeleteUserDomainRoleById(context.Context, *DeleteUserDomainRoleByIdRequest) (*DeleteUserDomainRoleByIdResponse, error)
	UndeleteUserDomainRoleById(context.Context, *UndeleteUserDomainRoleByIdRequest) (*UndeleteUserDomainRoleByIdResponse, error)
	// dc.user_table_roles
	GetUserTableRoleById(context.Context, *GetUserTableRoleByIdRequest) (*GetUserTableRoleByIdResponse, error)
	GetUserTableRoles(context.Context, *GetUserTableRolesRequest) (*GetUserTableRolesResponse, error)
	GetDeletedUserTableRoleById(context.Context, *GetDeletedUserTableRoleByIdRequest) (*GetDeletedUserTableRoleByIdResponse, error)
	GetDeletedUserTableRoles(context.Context, *GetDeletedUserTableRolesRequest) (*GetDeletedUserTableRolesResponse, error)
	CreateUserTableRole(context.Context, *CreateUserTableRoleRequest) (*CreateUserTableRoleResponse, error)
	UpdateUserTableRoleById(context.Context, *UpdateUserTableRoleByIdRequest) (*UpdateUserTableRoleByIdResponse, error)
	DeleteUserTableRoleById(context.Context, *DeleteUserTableRoleByIdRequest) (*DeleteUserTableRoleByIdResponse, error)
	UndeleteUserTableRoleById(context.Context, *UndeleteUserTableRoleByIdRequest) (*UndeleteUserTableRoleByIdResponse, error)
	mustEmbedUnimplementedUserDomainRolesServiceServer()
}

// UnimplementedUserDomainRolesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserDomainRolesServiceServer struct{}

func (UnimplementedUserDomainRolesServiceServer) GetDomainRoleById(context.Context, *GetDomainRoleByIdRequest) (*GetDomainRoleByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDomainRoleById not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) GetDomainRoles(context.Context, *GetDomainRolesRequest) (*GetDomainRolesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDomainRoles not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) GetDeletedDomainRoleById(context.Context, *GetDeletedDomainRoleByIdRequest) (*GetDeletedDomainRoleByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeletedDomainRoleById not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) GetDeletedDomainRoles(context.Context, *GetDeletedDomainRolesRequest) (*GetDeletedDomainRolesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeletedDomainRoles not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) CreateDomainRole(context.Context, *CreateDomainRoleRequest) (*CreateDomainRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDomainRole not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) UpdateDomainRoleById(context.Context, *UpdateDomainRoleByIdRequest) (*UpdateDomainRoleByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDomainRoleById not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) DeleteDomainRoleById(context.Context, *DeleteDomainRoleByIdRequest) (*DeleteDomainRoleByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDomainRoleById not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) UndeleteDomainRoleById(context.Context, *UndeleteDomainRoleByIdRequest) (*UndeleteDomainRoleByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UndeleteDomainRoleById not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) GetTableRoleById(context.Context, *GetTableRoleByIdRequest) (*GetTableRoleByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTableRoleById not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) GetTableRoles(context.Context, *GetTableRolesRequest) (*GetTableRolesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTableRoles not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) GetDeletedTableRoleById(context.Context, *GetDeletedTableRoleByIdRequest) (*GetDeletedTableRoleByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeletedTableRoleById not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) GetDeletedTableRoles(context.Context, *GetDeletedTableRolesRequest) (*GetDeletedTableRolesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeletedTableRoles not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) CreateTableRole(context.Context, *CreateTableRoleRequest) (*CreateTableRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTableRole not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) UpdateTableRoleById(context.Context, *UpdateTableRoleByIdRequest) (*UpdateTableRoleByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTableRoleById not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) DeleteTableRoleById(context.Context, *DeleteTableRoleByIdRequest) (*DeleteTableRoleByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTableRoleById not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) UndeleteTableRoleById(context.Context, *UndeleteTableRoleByIdRequest) (*UndeleteTableRoleByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UndeleteTableRoleById not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) GetUserDomainRoleById(context.Context, *GetUserDomainRoleByIdRequest) (*GetUserDomainRoleByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserDomainRoleById not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) GetUserDomainRoles(context.Context, *GetUserDomainRolesRequest) (*GetUserDomainRolesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserDomainRoles not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) GetDeletedUserDomainRoleById(context.Context, *GetDeletedUserDomainRoleByIdRequest) (*GetDeletedUserDomainRoleByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeletedUserDomainRoleById not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) GetDeletedUserDomainRoles(context.Context, *GetDeletedUserDomainRolesRequest) (*GetDeletedUserDomainRolesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeletedUserDomainRoles not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) CreateUserDomainRole(context.Context, *CreateUserDomainRoleRequest) (*CreateUserDomainRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserDomainRole not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) UpdateUserDomainRoleById(context.Context, *UpdateUserDomainRoleByIdRequest) (*UpdateUserDomainRoleByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserDomainRoleById not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) DeleteUserDomainRoleById(context.Context, *DeleteUserDomainRoleByIdRequest) (*DeleteUserDomainRoleByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserDomainRoleById not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) UndeleteUserDomainRoleById(context.Context, *UndeleteUserDomainRoleByIdRequest) (*UndeleteUserDomainRoleByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UndeleteUserDomainRoleById not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) GetUserTableRoleById(context.Context, *GetUserTableRoleByIdRequest) (*GetUserTableRoleByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserTableRoleById not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) GetUserTableRoles(context.Context, *GetUserTableRolesRequest) (*GetUserTableRolesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserTableRoles not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) GetDeletedUserTableRoleById(context.Context, *GetDeletedUserTableRoleByIdRequest) (*GetDeletedUserTableRoleByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeletedUserTableRoleById not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) GetDeletedUserTableRoles(context.Context, *GetDeletedUserTableRolesRequest) (*GetDeletedUserTableRolesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeletedUserTableRoles not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) CreateUserTableRole(context.Context, *CreateUserTableRoleRequest) (*CreateUserTableRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserTableRole not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) UpdateUserTableRoleById(context.Context, *UpdateUserTableRoleByIdRequest) (*UpdateUserTableRoleByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserTableRoleById not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) DeleteUserTableRoleById(context.Context, *DeleteUserTableRoleByIdRequest) (*DeleteUserTableRoleByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserTableRoleById not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) UndeleteUserTableRoleById(context.Context, *UndeleteUserTableRoleByIdRequest) (*UndeleteUserTableRoleByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UndeleteUserTableRoleById not implemented")
}
func (UnimplementedUserDomainRolesServiceServer) mustEmbedUnimplementedUserDomainRolesServiceServer() {
}
func (UnimplementedUserDomainRolesServiceServer) testEmbeddedByValue() {}

// UnsafeUserDomainRolesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserDomainRolesServiceServer will
// result in compilation errors.
type UnsafeUserDomainRolesServiceServer interface {
	mustEmbedUnimplementedUserDomainRolesServiceServer()
}

func RegisterUserDomainRolesServiceServer(s grpc.ServiceRegistrar, srv UserDomainRolesServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserDomainRolesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserDomainRolesService_ServiceDesc, srv)
}

func _UserDomainRolesService_GetDomainRoleById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDomainRoleByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).GetDomainRoleById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_GetDomainRoleById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).GetDomainRoleById(ctx, req.(*GetDomainRoleByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_GetDomainRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDomainRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).GetDomainRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_GetDomainRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).GetDomainRoles(ctx, req.(*GetDomainRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_GetDeletedDomainRoleById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeletedDomainRoleByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).GetDeletedDomainRoleById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_GetDeletedDomainRoleById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).GetDeletedDomainRoleById(ctx, req.(*GetDeletedDomainRoleByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_GetDeletedDomainRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeletedDomainRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).GetDeletedDomainRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_GetDeletedDomainRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).GetDeletedDomainRoles(ctx, req.(*GetDeletedDomainRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_CreateDomainRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDomainRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).CreateDomainRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_CreateDomainRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).CreateDomainRole(ctx, req.(*CreateDomainRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_UpdateDomainRoleById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDomainRoleByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).UpdateDomainRoleById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_UpdateDomainRoleById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).UpdateDomainRoleById(ctx, req.(*UpdateDomainRoleByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_DeleteDomainRoleById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDomainRoleByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).DeleteDomainRoleById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_DeleteDomainRoleById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).DeleteDomainRoleById(ctx, req.(*DeleteDomainRoleByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_UndeleteDomainRoleById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UndeleteDomainRoleByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).UndeleteDomainRoleById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_UndeleteDomainRoleById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).UndeleteDomainRoleById(ctx, req.(*UndeleteDomainRoleByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_GetTableRoleById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTableRoleByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).GetTableRoleById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_GetTableRoleById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).GetTableRoleById(ctx, req.(*GetTableRoleByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_GetTableRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTableRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).GetTableRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_GetTableRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).GetTableRoles(ctx, req.(*GetTableRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_GetDeletedTableRoleById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeletedTableRoleByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).GetDeletedTableRoleById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_GetDeletedTableRoleById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).GetDeletedTableRoleById(ctx, req.(*GetDeletedTableRoleByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_GetDeletedTableRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeletedTableRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).GetDeletedTableRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_GetDeletedTableRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).GetDeletedTableRoles(ctx, req.(*GetDeletedTableRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_CreateTableRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTableRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).CreateTableRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_CreateTableRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).CreateTableRole(ctx, req.(*CreateTableRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_UpdateTableRoleById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTableRoleByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).UpdateTableRoleById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_UpdateTableRoleById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).UpdateTableRoleById(ctx, req.(*UpdateTableRoleByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_DeleteTableRoleById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTableRoleByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).DeleteTableRoleById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_DeleteTableRoleById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).DeleteTableRoleById(ctx, req.(*DeleteTableRoleByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_UndeleteTableRoleById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UndeleteTableRoleByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).UndeleteTableRoleById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_UndeleteTableRoleById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).UndeleteTableRoleById(ctx, req.(*UndeleteTableRoleByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_GetUserDomainRoleById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserDomainRoleByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).GetUserDomainRoleById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_GetUserDomainRoleById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).GetUserDomainRoleById(ctx, req.(*GetUserDomainRoleByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_GetUserDomainRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserDomainRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).GetUserDomainRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_GetUserDomainRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).GetUserDomainRoles(ctx, req.(*GetUserDomainRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_GetDeletedUserDomainRoleById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeletedUserDomainRoleByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).GetDeletedUserDomainRoleById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_GetDeletedUserDomainRoleById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).GetDeletedUserDomainRoleById(ctx, req.(*GetDeletedUserDomainRoleByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_GetDeletedUserDomainRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeletedUserDomainRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).GetDeletedUserDomainRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_GetDeletedUserDomainRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).GetDeletedUserDomainRoles(ctx, req.(*GetDeletedUserDomainRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_CreateUserDomainRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserDomainRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).CreateUserDomainRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_CreateUserDomainRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).CreateUserDomainRole(ctx, req.(*CreateUserDomainRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_UpdateUserDomainRoleById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserDomainRoleByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).UpdateUserDomainRoleById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_UpdateUserDomainRoleById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).UpdateUserDomainRoleById(ctx, req.(*UpdateUserDomainRoleByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_DeleteUserDomainRoleById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserDomainRoleByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).DeleteUserDomainRoleById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_DeleteUserDomainRoleById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).DeleteUserDomainRoleById(ctx, req.(*DeleteUserDomainRoleByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_UndeleteUserDomainRoleById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UndeleteUserDomainRoleByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).UndeleteUserDomainRoleById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_UndeleteUserDomainRoleById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).UndeleteUserDomainRoleById(ctx, req.(*UndeleteUserDomainRoleByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_GetUserTableRoleById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTableRoleByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).GetUserTableRoleById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_GetUserTableRoleById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).GetUserTableRoleById(ctx, req.(*GetUserTableRoleByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_GetUserTableRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTableRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).GetUserTableRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_GetUserTableRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).GetUserTableRoles(ctx, req.(*GetUserTableRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_GetDeletedUserTableRoleById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeletedUserTableRoleByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).GetDeletedUserTableRoleById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_GetDeletedUserTableRoleById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).GetDeletedUserTableRoleById(ctx, req.(*GetDeletedUserTableRoleByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_GetDeletedUserTableRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeletedUserTableRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).GetDeletedUserTableRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_GetDeletedUserTableRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).GetDeletedUserTableRoles(ctx, req.(*GetDeletedUserTableRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_CreateUserTableRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserTableRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).CreateUserTableRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_CreateUserTableRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).CreateUserTableRole(ctx, req.(*CreateUserTableRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_UpdateUserTableRoleById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserTableRoleByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).UpdateUserTableRoleById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_UpdateUserTableRoleById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).UpdateUserTableRoleById(ctx, req.(*UpdateUserTableRoleByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_DeleteUserTableRoleById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserTableRoleByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).DeleteUserTableRoleById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_DeleteUserTableRoleById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).DeleteUserTableRoleById(ctx, req.(*DeleteUserTableRoleByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDomainRolesService_UndeleteUserTableRoleById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UndeleteUserTableRoleByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDomainRolesServiceServer).UndeleteUserTableRoleById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserDomainRolesService_UndeleteUserTableRoleById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDomainRolesServiceServer).UndeleteUserTableRoleById(ctx, req.(*UndeleteUserTableRoleByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserDomainRolesService_ServiceDesc is the grpc.ServiceDesc for UserDomainRolesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserDomainRolesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user_domain_roles.v1.UserDomainRolesService",
	HandlerType: (*UserDomainRolesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDomainRoleById",
			Handler:    _UserDomainRolesService_GetDomainRoleById_Handler,
		},
		{
			MethodName: "GetDomainRoles",
			Handler:    _UserDomainRolesService_GetDomainRoles_Handler,
		},
		{
			MethodName: "GetDeletedDomainRoleById",
			Handler:    _UserDomainRolesService_GetDeletedDomainRoleById_Handler,
		},
		{
			MethodName: "GetDeletedDomainRoles",
			Handler:    _UserDomainRolesService_GetDeletedDomainRoles_Handler,
		},
		{
			MethodName: "CreateDomainRole",
			Handler:    _UserDomainRolesService_CreateDomainRole_Handler,
		},
		{
			MethodName: "UpdateDomainRoleById",
			Handler:    _UserDomainRolesService_UpdateDomainRoleById_Handler,
		},
		{
			MethodName: "DeleteDomainRoleById",
			Handler:    _UserDomainRolesService_DeleteDomainRoleById_Handler,
		},
		{
			MethodName: "UndeleteDomainRoleById",
			Handler:    _UserDomainRolesService_UndeleteDomainRoleById_Handler,
		},
		{
			MethodName: "GetTableRoleById",
			Handler:    _UserDomainRolesService_GetTableRoleById_Handler,
		},
		{
			MethodName: "GetTableRoles",
			Handler:    _UserDomainRolesService_GetTableRoles_Handler,
		},
		{
			MethodName: "GetDeletedTableRoleById",
			Handler:    _UserDomainRolesService_GetDeletedTableRoleById_Handler,
		},
		{
			MethodName: "GetDeletedTableRoles",
			Handler:    _UserDomainRolesService_GetDeletedTableRoles_Handler,
		},
		{
			MethodName: "CreateTableRole",
			Handler:    _UserDomainRolesService_CreateTableRole_Handler,
		},
		{
			MethodName: "UpdateTableRoleById",
			Handler:    _UserDomainRolesService_UpdateTableRoleById_Handler,
		},
		{
			MethodName: "DeleteTableRoleById",
			Handler:    _UserDomainRolesService_DeleteTableRoleById_Handler,
		},
		{
			MethodName: "UndeleteTableRoleById",
			Handler:    _UserDomainRolesService_UndeleteTableRoleById_Handler,
		},
		{
			MethodName: "GetUserDomainRoleById",
			Handler:    _UserDomainRolesService_GetUserDomainRoleById_Handler,
		},
		{
			MethodName: "GetUserDomainRoles",
			Handler:    _UserDomainRolesService_GetUserDomainRoles_Handler,
		},
		{
			MethodName: "GetDeletedUserDomainRoleById",
			Handler:    _UserDomainRolesService_GetDeletedUserDomainRoleById_Handler,
		},
		{
			MethodName: "GetDeletedUserDomainRoles",
			Handler:    _UserDomainRolesService_GetDeletedUserDomainRoles_Handler,
		},
		{
			MethodName: "CreateUserDomainRole",
			Handler:    _UserDomainRolesService_CreateUserDomainRole_Handler,
		},
		{
			MethodName: "UpdateUserDomainRoleById",
			Handler:    _UserDomainRolesService_UpdateUserDomainRoleById_Handler,
		},
		{
			MethodName: "DeleteUserDomainRoleById",
			Handler:    _UserDomainRolesService_DeleteUserDomainRoleById_Handler,
		},
		{
			MethodName: "UndeleteUserDomainRoleById",
			Handler:    _UserDomainRolesService_UndeleteUserDomainRoleById_Handler,
		},
		{
			MethodName: "GetUserTableRoleById",
			Handler:    _UserDomainRolesService_GetUserTableRoleById_Handler,
		},
		{
			MethodName: "GetUserTableRoles",
			Handler:    _UserDomainRolesService_GetUserTableRoles_Handler,
		},
		{
			MethodName: "GetDeletedUserTableRoleById",
			Handler:    _UserDomainRolesService_GetDeletedUserTableRoleById_Handler,
		},
		{
			MethodName: "GetDeletedUserTableRoles",
			Handler:    _UserDomainRolesService_GetDeletedUserTableRoles_Handler,
		},
		{
			MethodName: "CreateUserTableRole",
			Handler:    _UserDomainRolesService_CreateUserTableRole_Handler,
		},
		{
			MethodName: "UpdateUserTableRoleById",
			Handler:    _UserDomainRolesService_UpdateUserTableRoleById_Handler,
		},
		{
			MethodName: "DeleteUserTableRoleById",
			Handler:    _UserDomainRolesService_DeleteUserTableRoleById_Handler,
		},
		{
			MethodName: "UndeleteUserTableRoleById",
			Handler:    _UserDomainRolesService_UndeleteUserTableRoleById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_domain_roles/v1/user_domain_roles.proto",
}
