// Файл сгенерирован программой SG Buddy https://github.com/konstantin-suspitsyn/sg_buddy
// Правки будут затёрты при следующей генерации: правьте настройки, а не этот файл.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tables/v1/tables.proto

package tablesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Постраничность: одна на файл, поля одни и те же везде.
type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	TotalItems    int64                  `protobuf:"varint,3,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	TotalPages    int64                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_tables_v1_tables_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *Pagination) GetTotalItems() int64 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *Pagination) GetTotalPages() int64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// Строка таблицы dc.alias: все колонки, как их вернёт SELECT *.
type Alias struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,6,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	UserId        int64                  `protobuf:"varint,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alias) Reset() {
	*x = Alias{}
	mi := &file_tables_v1_tables_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alias) ProtoMessage() {}

func (x *Alias) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alias.ProtoReflect.Descriptor instead.
func (*Alias) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{1}
}

func (x *Alias) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Alias) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Alias) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Alias) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Alias) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Alias) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *Alias) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Вставка CreateAlias: параметры вызова.
type CreateAliasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ExternalId    string                 `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAliasRequest) Reset() {
	*x = CreateAliasRequest{}
	mi := &file_tables_v1_tables_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAliasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAliasRequest) ProtoMessage() {}

func (x *CreateAliasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAliasRequest.ProtoReflect.Descriptor instead.
func (*CreateAliasRequest) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAliasRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAliasRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAliasRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

// Вставка CreateAlias: одна строка.
type CreateAliasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         *Alias                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAliasResponse) Reset() {
	*x = CreateAliasResponse{}
	mi := &file_tables_v1_tables_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAliasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAliasResponse) ProtoMessage() {}

func (x *CreateAliasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAliasResponse.ProtoReflect.Descriptor instead.
func (*CreateAliasResponse) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAliasResponse) GetAlias() *Alias {
	if x != nil {
		return x.Alias
	}
	return nil
}

// Выборка GetAliasById: параметры вызова.
type GetAliasByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAliasByIdRequest) Reset() {
	*x = GetAliasByIdRequest{}
	mi := &file_tables_v1_tables_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAliasByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAliasByIdRequest) ProtoMessage() {}

func (x *GetAliasByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAliasByIdRequest.ProtoReflect.Descriptor instead.
func (*GetAliasByIdRequest) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{4}
}

func (x *GetAliasByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Выборка GetAliasById: одна строка.
type GetAliasByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         *Alias                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAliasByIdResponse) Reset() {
	*x = GetAliasByIdResponse{}
	mi := &file_tables_v1_tables_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAliasByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAliasByIdResponse) ProtoMessage() {}

func (x *GetAliasByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAliasByIdResponse.ProtoReflect.Descriptor instead.
func (*GetAliasByIdResponse) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{5}
}

func (x *GetAliasByIdResponse) GetAlias() *Alias {
	if x != nil {
		return x.Alias
	}
	return nil
}

// Выборка GetAliasesDeleted: параметры вызова. Порядок по умолчанию — id.
type GetAliasesDeletedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// допустимые значения: ASC, DESC
	Order         string `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	PageLimit     int32  `protobuf:"varint,2,opt,name=page_limit,json=pageLimit,proto3" json:"page_limit,omitempty"`
	Page          int32  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAliasesDeletedRequest) Reset() {
	*x = GetAliasesDeletedRequest{}
	mi := &file_tables_v1_tables_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAliasesDeletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAliasesDeletedRequest) ProtoMessage() {}

func (x *GetAliasesDeletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAliasesDeletedRequest.ProtoReflect.Descriptor instead.
func (*GetAliasesDeletedRequest) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{6}
}

func (x *GetAliasesDeletedRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *GetAliasesDeletedRequest) GetPageLimit() int32 {
	if x != nil {
		return x.PageLimit
	}
	return 0
}

func (x *GetAliasesDeletedRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

// Выборка GetAliasesDeleted: страница данных и пагинация.
type GetAliasesDeletedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Alias               `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAliasesDeletedResponse) Reset() {
	*x = GetAliasesDeletedResponse{}
	mi := &file_tables_v1_tables_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAliasesDeletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAliasesDeletedResponse) ProtoMessage() {}

func (x *GetAliasesDeletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAliasesDeletedResponse.ProtoReflect.Descriptor instead.
func (*GetAliasesDeletedResponse) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{7}
}

func (x *GetAliasesDeletedResponse) GetData() []*Alias {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetAliasesDeletedResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Выборка GetAliases: параметры вызова. Порядок по умолчанию — id.
type GetAliasesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// допустимые значения: ASC, DESC
	Order         string `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	PageLimit     int32  `protobuf:"varint,2,opt,name=page_limit,json=pageLimit,proto3" json:"page_limit,omitempty"`
	Page          int32  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAliasesRequest) Reset() {
	*x = GetAliasesRequest{}
	mi := &file_tables_v1_tables_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAliasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAliasesRequest) ProtoMessage() {}

func (x *GetAliasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAliasesRequest.ProtoReflect.Descriptor instead.
func (*GetAliasesRequest) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{8}
}

func (x *GetAliasesRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *GetAliasesRequest) GetPageLimit() int32 {
	if x != nil {
		return x.PageLimit
	}
	return 0
}

func (x *GetAliasesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

// Выборка GetAliases: страница данных и пагинация.
type GetAliasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Alias               `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAliasesResponse) Reset() {
	*x = GetAliasesResponse{}
	mi := &file_tables_v1_tables_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAliasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAliasesResponse) ProtoMessage() {}

func (x *GetAliasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAliasesResponse.ProtoReflect.Descriptor instead.
func (*GetAliasesResponse) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{9}
}

func (x *GetAliasesResponse) GetData() []*Alias {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetAliasesResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Изменение UpdateAliasById: параметры вызова.
type UpdateAliasByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,3,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	ExternalId    string                 `protobuf:"bytes,4,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Id            int64                  `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAliasByIdRequest) Reset() {
	*x = UpdateAliasByIdRequest{}
	mi := &file_tables_v1_tables_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAliasByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAliasByIdRequest) ProtoMessage() {}

func (x *UpdateAliasByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAliasByIdRequest.ProtoReflect.Descriptor instead.
func (*UpdateAliasByIdRequest) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateAliasByIdRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAliasByIdRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateAliasByIdRequest) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *UpdateAliasByIdRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *UpdateAliasByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Изменение UpdateAliasById: ответ пустой — запрос ничего не возвращает.
type UpdateAliasByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAliasByIdResponse) Reset() {
	*x = UpdateAliasByIdResponse{}
	mi := &file_tables_v1_tables_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAliasByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAliasByIdResponse) ProtoMessage() {}

func (x *UpdateAliasByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAliasByIdResponse.ProtoReflect.Descriptor instead.
func (*UpdateAliasByIdResponse) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{11}
}

// Мягкое удаление DeleteAliasById: параметры вызова.
type DeleteAliasByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAliasByIdRequest) Reset() {
	*x = DeleteAliasByIdRequest{}
	mi := &file_tables_v1_tables_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAliasByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAliasByIdRequest) ProtoMessage() {}

func (x *DeleteAliasByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAliasByIdRequest.ProtoReflect.Descriptor instead.
func (*DeleteAliasByIdRequest) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteAliasByIdRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *DeleteAliasByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Мягкое удаление DeleteAliasById: ответ пустой — запрос ничего не возвращает.
type DeleteAliasByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAliasByIdResponse) Reset() {
	*x = DeleteAliasByIdResponse{}
	mi := &file_tables_v1_tables_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAliasByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAliasByIdResponse) ProtoMessage() {}

func (x *DeleteAliasByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAliasByIdResponse.ProtoReflect.Descriptor instead.
func (*DeleteAliasByIdResponse) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{13}
}

// Обратное удаление UndeleteAliasById: параметры вызова.
type UndeleteAliasByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndeleteAliasByIdRequest) Reset() {
	*x = UndeleteAliasByIdRequest{}
	mi := &file_tables_v1_tables_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndeleteAliasByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndeleteAliasByIdRequest) ProtoMessage() {}

func (x *UndeleteAliasByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndeleteAliasByIdRequest.ProtoReflect.Descriptor instead.
func (*UndeleteAliasByIdRequest) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{14}
}

func (x *UndeleteAliasByIdRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *UndeleteAliasByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Обратное удаление UndeleteAliasById: ответ пустой — запрос ничего не возвращает.
type UndeleteAliasByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndeleteAliasByIdResponse) Reset() {
	*x = UndeleteAliasByIdResponse{}
	mi := &file_tables_v1_tables_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndeleteAliasByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndeleteAliasByIdResponse) ProtoMessage() {}

func (x *UndeleteAliasByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndeleteAliasByIdResponse.ProtoReflect.Descriptor instead.
func (*UndeleteAliasByIdResponse) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{15}
}

// Строка таблицы dc.user: все колонки, как их вернёт SELECT *.
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int64                 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,5,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	ExternalId    string                 `protobuf:"bytes,6,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_tables_v1_tables_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{16}
}

func (x *User) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *User) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

// Вставка CreateUser: параметры вызова.
type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ExternalId    string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_tables_v1_tables_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{17}
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

// Вставка CreateUser: одна строка.
type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_tables_v1_tables_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{18}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Выборка GetUserByExternalId: параметры вызова.
type GetUserByExternalIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByExternalIdRequest) Reset() {
	*x = GetUserByExternalIdRequest{}
	mi := &file_tables_v1_tables_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByExternalIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByExternalIdRequest) ProtoMessage() {}

func (x *GetUserByExternalIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByExternalIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserByExternalIdRequest) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{19}
}

func (x *GetUserByExternalIdRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

// Выборка GetUserByExternalId: одна строка.
type GetUserByExternalIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByExternalIdResponse) Reset() {
	*x = GetUserByExternalIdResponse{}
	mi := &file_tables_v1_tables_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByExternalIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByExternalIdResponse) ProtoMessage() {}

func (x *GetUserByExternalIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByExternalIdResponse.ProtoReflect.Descriptor instead.
func (*GetUserByExternalIdResponse) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{20}
}

func (x *GetUserByExternalIdResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Выборка GetUsers: параметры вызова. Порядок по умолчанию — id.
type GetUsersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// допустимые значения: ASC, DESC
	Order         string `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	PageLimit     int32  `protobuf:"varint,2,opt,name=page_limit,json=pageLimit,proto3" json:"page_limit,omitempty"`
	Page          int32  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersRequest) Reset() {
	*x = GetUsersRequest{}
	mi := &file_tables_v1_tables_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersRequest) ProtoMessage() {}

func (x *GetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersRequest.ProtoReflect.Descriptor instead.
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{21}
}

func (x *GetUsersRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *GetUsersRequest) GetPageLimit() int32 {
	if x != nil {
		return x.PageLimit
	}
	return 0
}

func (x *GetUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

// Выборка GetUsers: страница данных и пагинация.
type GetUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*User                `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersResponse) Reset() {
	*x = GetUsersResponse{}
	mi := &file_tables_v1_tables_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersResponse) ProtoMessage() {}

func (x *GetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersResponse.ProtoReflect.Descriptor instead.
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{22}
}

func (x *GetUsersResponse) GetData() []*User {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetUsersResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Строка таблицы dc.host: все колонки, как их вернёт SELECT *.
type Host struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	HostEnv       string                 `protobuf:"bytes,4,opt,name=host_env,json=hostEnv,proto3" json:"host_env,omitempty"`
	PortEnv       string                 `protobuf:"bytes,5,opt,name=port_env,json=portEnv,proto3" json:"port_env,omitempty"`
	UsernameEnv   string                 `protobuf:"bytes,6,opt,name=username_env,json=usernameEnv,proto3" json:"username_env,omitempty"`
	PasswordEnv   string                 `protobuf:"bytes,7,opt,name=password_env,json=passwordEnv,proto3" json:"password_env,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,8,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UserId        int64                  `protobuf:"varint,11,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Host) Reset() {
	*x = Host{}
	mi := &file_tables_v1_tables_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{23}
}

func (x *Host) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Host) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Host) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Host) GetHostEnv() string {
	if x != nil {
		return x.HostEnv
	}
	return ""
}

func (x *Host) GetPortEnv() string {
	if x != nil {
		return x.PortEnv
	}
	return ""
}

func (x *Host) GetUsernameEnv() string {
	if x != nil {
		return x.UsernameEnv
	}
	return ""
}

func (x *Host) GetPasswordEnv() string {
	if x != nil {
		return x.PasswordEnv
	}
	return ""
}

func (x *Host) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *Host) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Host) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Host) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Вставка CreateHost: параметры вызова.
type CreateHostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	HostEnv       string                 `protobuf:"bytes,3,opt,name=host_env,json=hostEnv,proto3" json:"host_env,omitempty"`
	PortEnv       string                 `protobuf:"bytes,4,opt,name=port_env,json=portEnv,proto3" json:"port_env,omitempty"`
	UsernameEnv   string                 `protobuf:"bytes,5,opt,name=username_env,json=usernameEnv,proto3" json:"username_env,omitempty"`
	PasswordEnv   string                 `protobuf:"bytes,6,opt,name=password_env,json=passwordEnv,proto3" json:"password_env,omitempty"`
	ExternalId    string                 `protobuf:"bytes,7,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHostRequest) Reset() {
	*x = CreateHostRequest{}
	mi := &file_tables_v1_tables_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHostRequest) ProtoMessage() {}

func (x *CreateHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHostRequest.ProtoReflect.Descriptor instead.
func (*CreateHostRequest) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{24}
}

func (x *CreateHostRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateHostRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateHostRequest) GetHostEnv() string {
	if x != nil {
		return x.HostEnv
	}
	return ""
}

func (x *CreateHostRequest) GetPortEnv() string {
	if x != nil {
		return x.PortEnv
	}
	return ""
}

func (x *CreateHostRequest) GetUsernameEnv() string {
	if x != nil {
		return x.UsernameEnv
	}
	return ""
}

func (x *CreateHostRequest) GetPasswordEnv() string {
	if x != nil {
		return x.PasswordEnv
	}
	return ""
}

func (x *CreateHostRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

// Вставка CreateHost: одна строка.
type CreateHostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          *Host                  `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHostResponse) Reset() {
	*x = CreateHostResponse{}
	mi := &file_tables_v1_tables_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHostResponse) ProtoMessage() {}

func (x *CreateHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHostResponse.ProtoReflect.Descriptor instead.
func (*CreateHostResponse) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{25}
}

func (x *CreateHostResponse) GetHost() *Host {
	if x != nil {
		return x.Host
	}
	return nil
}

// Выборка GetHostById: параметры вызова.
type GetHostByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostByIdRequest) Reset() {
	*x = GetHostByIdRequest{}
	mi := &file_tables_v1_tables_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostByIdRequest) ProtoMessage() {}

func (x *GetHostByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostByIdRequest.ProtoReflect.Descriptor instead.
func (*GetHostByIdRequest) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{26}
}

func (x *GetHostByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Выборка GetHostById: одна строка.
type GetHostByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          *Host                  `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostByIdResponse) Reset() {
	*x = GetHostByIdResponse{}
	mi := &file_tables_v1_tables_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostByIdResponse) ProtoMessage() {}

func (x *GetHostByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostByIdResponse.ProtoReflect.Descriptor instead.
func (*GetHostByIdResponse) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{27}
}

func (x *GetHostByIdResponse) GetHost() *Host {
	if x != nil {
		return x.Host
	}
	return nil
}

// Выборка GetHosts: параметры вызова. Порядок по умолчанию — id.
type GetHostsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// допустимые значения: ASC, DESC
	Order         string `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	PageLimit     int32  `protobuf:"varint,2,opt,name=page_limit,json=pageLimit,proto3" json:"page_limit,omitempty"`
	Page          int32  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostsRequest) Reset() {
	*x = GetHostsRequest{}
	mi := &file_tables_v1_tables_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostsRequest) ProtoMessage() {}

func (x *GetHostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostsRequest.ProtoReflect.Descriptor instead.
func (*GetHostsRequest) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{28}
}

func (x *GetHostsRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *GetHostsRequest) GetPageLimit() int32 {
	if x != nil {
		return x.PageLimit
	}
	return 0
}

func (x *GetHostsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

// Выборка GetHosts: страница данных и пагинация.
type GetHostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Host                `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostsResponse) Reset() {
	*x = GetHostsResponse{}
	mi := &file_tables_v1_tables_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostsResponse) ProtoMessage() {}

func (x *GetHostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostsResponse.ProtoReflect.Descriptor instead.
func (*GetHostsResponse) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{29}
}

func (x *GetHostsResponse) GetData() []*Host {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetHostsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Выборка GetHostsSearchName: параметры вызова. Порядок по умолчанию — id.
type GetHostsSearchNameRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SearchName string                 `protobuf:"bytes,1,opt,name=search_name,json=searchName,proto3" json:"search_name,omitempty"`
	// допустимые значения: ASC, DESC
	Order         string `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	PageLimit     int32  `protobuf:"varint,3,opt,name=page_limit,json=pageLimit,proto3" json:"page_limit,omitempty"`
	Page          int32  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostsSearchNameRequest) Reset() {
	*x = GetHostsSearchNameRequest{}
	mi := &file_tables_v1_tables_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostsSearchNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostsSearchNameRequest) ProtoMessage() {}

func (x *GetHostsSearchNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostsSearchNameRequest.ProtoReflect.Descriptor instead.
func (*GetHostsSearchNameRequest) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{30}
}

func (x *GetHostsSearchNameRequest) GetSearchName() string {
	if x != nil {
		return x.SearchName
	}
	return ""
}

func (x *GetHostsSearchNameRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *GetHostsSearchNameRequest) GetPageLimit() int32 {
	if x != nil {
		return x.PageLimit
	}
	return 0
}

func (x *GetHostsSearchNameRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

// Выборка GetHostsSearchName: страница данных и пагинация.
type GetHostsSearchNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Host                `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostsSearchNameResponse) Reset() {
	*x = GetHostsSearchNameResponse{}
	mi := &file_tables_v1_tables_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostsSearchNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostsSearchNameResponse) ProtoMessage() {}

func (x *GetHostsSearchNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostsSearchNameResponse.ProtoReflect.Descriptor instead.
func (*GetHostsSearchNameResponse) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{31}
}

func (x *GetHostsSearchNameResponse) GetData() []*Host {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetHostsSearchNameResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Выборка GetHostDeleted: параметры вызова. Порядок по умолчанию — id.
type GetHostDeletedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// допустимые значения: ASC, DESC
	Order         string `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	PageLimit     int32  `protobuf:"varint,2,opt,name=page_limit,json=pageLimit,proto3" json:"page_limit,omitempty"`
	Page          int32  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostDeletedRequest) Reset() {
	*x = GetHostDeletedRequest{}
	mi := &file_tables_v1_tables_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostDeletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostDeletedRequest) ProtoMessage() {}

func (x *GetHostDeletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostDeletedRequest.ProtoReflect.Descriptor instead.
func (*GetHostDeletedRequest) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{32}
}

func (x *GetHostDeletedRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *GetHostDeletedRequest) GetPageLimit() int32 {
	if x != nil {
		return x.PageLimit
	}
	return 0
}

func (x *GetHostDeletedRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

// Выборка GetHostDeleted: страница данных и пагинация.
type GetHostDeletedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Host                `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostDeletedResponse) Reset() {
	*x = GetHostDeletedResponse{}
	mi := &file_tables_v1_tables_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostDeletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostDeletedResponse) ProtoMessage() {}

func (x *GetHostDeletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostDeletedResponse.ProtoReflect.Descriptor instead.
func (*GetHostDeletedResponse) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{33}
}

func (x *GetHostDeletedResponse) GetData() []*Host {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetHostDeletedResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Изменение UpdateHostById: параметры вызова.
type UpdateHostByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	HostEnv       string                 `protobuf:"bytes,4,opt,name=host_env,json=hostEnv,proto3" json:"host_env,omitempty"`
	PortEnv       string                 `protobuf:"bytes,5,opt,name=port_env,json=portEnv,proto3" json:"port_env,omitempty"`
	UsernameEnv   string                 `protobuf:"bytes,6,opt,name=username_env,json=usernameEnv,proto3" json:"username_env,omitempty"`
	PasswordEnv   string                 `protobuf:"bytes,7,opt,name=password_env,json=passwordEnv,proto3" json:"password_env,omitempty"`
	ExternalId    string                 `protobuf:"bytes,8,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHostByIdRequest) Reset() {
	*x = UpdateHostByIdRequest{}
	mi := &file_tables_v1_tables_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHostByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHostByIdRequest) ProtoMessage() {}

func (x *UpdateHostByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHostByIdRequest.ProtoReflect.Descriptor instead.
func (*UpdateHostByIdRequest) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{34}
}

func (x *UpdateHostByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateHostByIdRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateHostByIdRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateHostByIdRequest) GetHostEnv() string {
	if x != nil {
		return x.HostEnv
	}
	return ""
}

func (x *UpdateHostByIdRequest) GetPortEnv() string {
	if x != nil {
		return x.PortEnv
	}
	return ""
}

func (x *UpdateHostByIdRequest) GetUsernameEnv() string {
	if x != nil {
		return x.UsernameEnv
	}
	return ""
}

func (x *UpdateHostByIdRequest) GetPasswordEnv() string {
	if x != nil {
		return x.PasswordEnv
	}
	return ""
}

func (x *UpdateHostByIdRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

// Изменение UpdateHostById: ответ пустой — запрос ничего не возвращает.
type UpdateHostByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHostByIdResponse) Reset() {
	*x = UpdateHostByIdResponse{}
	mi := &file_tables_v1_tables_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHostByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHostByIdResponse) ProtoMessage() {}

func (x *UpdateHostByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHostByIdResponse.ProtoReflect.Descriptor instead.
func (*UpdateHostByIdResponse) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{35}
}

// Мягкое удаление DeleteHostById: параметры вызова.
type DeleteHostByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHostByIdRequest) Reset() {
	*x = DeleteHostByIdRequest{}
	mi := &file_tables_v1_tables_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHostByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHostByIdRequest) ProtoMessage() {}

func (x *DeleteHostByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHostByIdRequest.ProtoReflect.Descriptor instead.
func (*DeleteHostByIdRequest) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{36}
}

func (x *DeleteHostByIdRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *DeleteHostByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Мягкое удаление DeleteHostById: ответ пустой — запрос ничего не возвращает.
type DeleteHostByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHostByIdResponse) Reset() {
	*x = DeleteHostByIdResponse{}
	mi := &file_tables_v1_tables_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHostByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHostByIdResponse) ProtoMessage() {}

func (x *DeleteHostByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHostByIdResponse.ProtoReflect.Descriptor instead.
func (*DeleteHostByIdResponse) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{37}
}

// Обратное удаление UndeleteHostById: параметры вызова.
type UndeleteHostByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndeleteHostByIdRequest) Reset() {
	*x = UndeleteHostByIdRequest{}
	mi := &file_tables_v1_tables_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndeleteHostByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndeleteHostByIdRequest) ProtoMessage() {}

func (x *UndeleteHostByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndeleteHostByIdRequest.ProtoReflect.Descriptor instead.
func (*UndeleteHostByIdRequest) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{38}
}

func (x *UndeleteHostByIdRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *UndeleteHostByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Обратное удаление UndeleteHostById: ответ пустой — запрос ничего не возвращает.
type UndeleteHostByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndeleteHostByIdResponse) Reset() {
	*x = UndeleteHostByIdResponse{}
	mi := &file_tables_v1_tables_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndeleteHostByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndeleteHostByIdResponse) ProtoMessage() {}

func (x *UndeleteHostByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tables_v1_tables_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndeleteHostByIdResponse.ProtoReflect.Descriptor instead.
func (*UndeleteHostByIdResponse) Descriptor() ([]byte, []int) {
	return file_tables_v1_tables_proto_rawDescGZIP(), []int{39}
}

var File_tables_v1_tables_proto protoreflect.FileDescriptor

const file_tables_v1_tables_proto_rawDesc = "" +
	"\n" +
	"\x16tables/v1/tables.proto\x12\ttables.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"}\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage\x12\x1f\n" +
	"\vtotal_items\x18\x03 \x01(\x03R\n" +
	"totalItems\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x03R\n" +
	"totalPages\"\xfb\x01\n" +
	"\x05Alias\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x06 \x01(\bR\tisDeleted\x12\x17\n" +
	"\auser_id\x18\a \x01(\x03R\x06userId\"k\n" +
	"\x12CreateAliasRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1f\n" +
	"\vexternal_id\x18\x03 \x01(\tR\n" +
	"externalId\"=\n" +
	"\x13CreateAliasResponse\x12&\n" +
	"\x05alias\x18\x01 \x01(\v2\x10.tables.v1.AliasR\x05alias\"%\n" +
	"\x13GetAliasByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\">\n" +
	"\x14GetAliasByIdResponse\x12&\n" +
	"\x05alias\x18\x01 \x01(\v2\x10.tables.v1.AliasR\x05alias\"c\n" +
	"\x18GetAliasesDeletedRequest\x12\x14\n" +
	"\x05order\x18\x01 \x01(\tR\x05order\x12\x1d\n" +
	"\n" +
	"page_limit\x18\x02 \x01(\x05R\tpageLimit\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\"x\n" +
	"\x19GetAliasesDeletedResponse\x12$\n" +
	"\x04data\x18\x01 \x03(\v2\x10.tables.v1.AliasR\x04data\x125\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x15.tables.v1.PaginationR\n" +
	"pagination\"\\\n" +
	"\x11GetAliasesRequest\x12\x14\n" +
	"\x05order\x18\x01 \x01(\tR\x05order\x12\x1d\n" +
	"\n" +
	"page_limit\x18\x02 \x01(\x05R\tpageLimit\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\"q\n" +
	"\x12GetAliasesResponse\x12$\n" +
	"\x04data\x18\x01 \x03(\v2\x10.tables.v1.AliasR\x04data\x125\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x15.tables.v1.PaginationR\n" +
	"pagination\"\x9e\x01\n" +
	"\x16UpdateAliasByIdRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x03 \x01(\bR\tisDeleted\x12\x1f\n" +
	"\vexternal_id\x18\x04 \x01(\tR\n" +
	"externalId\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\x03R\x02id\"\x19\n" +
	"\x17UpdateAliasByIdResponse\"I\n" +
	"\x16DeleteAliasByIdRequest\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"\x19\n" +
	"\x17DeleteAliasByIdResponse\"K\n" +
	"\x18UndeleteAliasByIdRequest\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"\x1b\n" +
	"\x19UndeleteAliasByIdResponse\"\xec\x01\n" +
	"\x04User\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03H\x00R\x02id\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x05 \x01(\bR\tisDeleted\x12\x1f\n" +
	"\vexternal_id\x18\x06 \x01(\tR\n" +
	"externalIdB\x05\n" +
	"\x03_id\"H\n" +
	"\x11CreateUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\"9\n" +
	"\x12CreateUserResponse\x12#\n" +
	"\x04user\x18\x01 \x01(\v2\x0f.tables.v1.UserR\x04user\"=\n" +
	"\x1aGetUserByExternalIdRequest\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\"B\n" +
	"\x1bGetUserByExternalIdResponse\x12#\n" +
	"\x04user\x18\x01 \x01(\v2\x0f.tables.v1.UserR\x04user\"Z\n" +
	"\x0fGetUsersRequest\x12\x14\n" +
	"\x05order\x18\x01 \x01(\tR\x05order\x12\x1d\n" +
	"\n" +
	"page_limit\x18\x02 \x01(\x05R\tpageLimit\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\"n\n" +
	"\x10GetUsersResponse\x12#\n" +
	"\x04data\x18\x01 \x03(\v2\x0f.tables.v1.UserR\x04data\x125\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x15.tables.v1.PaginationR\n" +
	"pagination\"\xf6\x02\n" +
	"\x04Host\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bhost_env\x18\x04 \x01(\tR\ahostEnv\x12\x19\n" +
	"\bport_env\x18\x05 \x01(\tR\aportEnv\x12!\n" +
	"\fusername_env\x18\x06 \x01(\tR\vusernameEnv\x12!\n" +
	"\fpassword_env\x18\a \x01(\tR\vpasswordEnv\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\b \x01(\bR\tisDeleted\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x17\n" +
	"\auser_id\x18\v \x01(\x03R\x06userId\"\xe6\x01\n" +
	"\x11CreateHostRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x19\n" +
	"\bhost_env\x18\x03 \x01(\tR\ahostEnv\x12\x19\n" +
	"\bport_env\x18\x04 \x01(\tR\aportEnv\x12!\n" +
	"\fusername_env\x18\x05 \x01(\tR\vusernameEnv\x12!\n" +
	"\fpassword_env\x18\x06 \x01(\tR\vpasswordEnv\x12\x1f\n" +
	"\vexternal_id\x18\a \x01(\tR\n" +
	"externalId\"9\n" +
	"\x12CreateHostResponse\x12#\n" +
	"\x04host\x18\x01 \x01(\v2\x0f.tables.v1.HostR\x04host\"$\n" +
	"\x12GetHostByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\":\n" +
	"\x13GetHostByIdResponse\x12#\n" +
	"\x04host\x18\x01 \x01(\v2\x0f.tables.v1.HostR\x04host\"Z\n" +
	"\x0fGetHostsRequest\x12\x14\n" +
	"\x05order\x18\x01 \x01(\tR\x05order\x12\x1d\n" +
	"\n" +
	"page_limit\x18\x02 \x01(\x05R\tpageLimit\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\"n\n" +
	"\x10GetHostsResponse\x12#\n" +
	"\x04data\x18\x01 \x03(\v2\x0f.tables.v1.HostR\x04data\x125\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x15.tables.v1.PaginationR\n" +
	"pagination\"\x85\x01\n" +
	"\x19GetHostsSearchNameRequest\x12\x1f\n" +
	"\vsearch_name\x18\x01 \x01(\tR\n" +
	"searchName\x12\x14\n" +
	"\x05order\x18\x02 \x01(\tR\x05order\x12\x1d\n" +
	"\n" +
	"page_limit\x18\x03 \x01(\x05R\tpageLimit\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\"x\n" +
	"\x1aGetHostsSearchNameResponse\x12#\n" +
	"\x04data\x18\x01 \x03(\v2\x0f.tables.v1.HostR\x04data\x125\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x15.tables.v1.PaginationR\n" +
	"pagination\"`\n" +
	"\x15GetHostDeletedRequest\x12\x14\n" +
	"\x05order\x18\x01 \x01(\tR\x05order\x12\x1d\n" +
	"\n" +
	"page_limit\x18\x02 \x01(\x05R\tpageLimit\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\"t\n" +
	"\x16GetHostDeletedResponse\x12#\n" +
	"\x04data\x18\x01 \x03(\v2\x0f.tables.v1.HostR\x04data\x125\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x15.tables.v1.PaginationR\n" +
	"pagination\"\xfa\x01\n" +
	"\x15UpdateHostByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bhost_env\x18\x04 \x01(\tR\ahostEnv\x12\x19\n" +
	"\bport_env\x18\x05 \x01(\tR\aportEnv\x12!\n" +
	"\fusername_env\x18\x06 \x01(\tR\vusernameEnv\x12!\n" +
	"\fpassword_env\x18\a \x01(\tR\vpasswordEnv\x12\x1f\n" +
	"\vexternal_id\x18\b \x01(\tR\n" +
	"externalId\"\x18\n" +
	"\x16UpdateHostByIdResponse\"H\n" +
	"\x15DeleteHostByIdRequest\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"\x18\n" +
	"\x16DeleteHostByIdResponse\"J\n" +
	"\x17UndeleteHostByIdRequest\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"\x1a\n" +
	"\x18UndeleteHostByIdResponse2\xec\x04\n" +
	"\fAliasService\x12L\n" +
	"\vCreateAlias\x12\x1d.tables.v1.CreateAliasRequest\x1a\x1e.tables.v1.CreateAliasResponse\x12O\n" +
	"\fGetAliasById\x12\x1e.tables.v1.GetAliasByIdRequest\x1a\x1f.tables.v1.GetAliasByIdResponse\x12^\n" +
	"\x11GetAliasesDeleted\x12#.tables.v1.GetAliasesDeletedRequest\x1a$.tables.v1.GetAliasesDeletedResponse\x12I\n" +
	"\n" +
	"GetAliases\x12\x1c.tables.v1.GetAliasesRequest\x1a\x1d.tables.v1.GetAliasesResponse\x12X\n" +
	"\x0fUpdateAliasById\x12!.tables.v1.UpdateAliasByIdRequest\x1a\".tables.v1.UpdateAliasByIdResponse\x12X\n" +
	"\x0fDeleteAliasById\x12!.tables.v1.DeleteAliasByIdRequest\x1a\".tables.v1.DeleteAliasByIdResponse\x12^\n" +
	"\x11UndeleteAliasById\x12#.tables.v1.UndeleteAliasByIdRequest\x1a$.tables.v1.UndeleteAliasByIdResponse2\x83\x02\n" +
	"\vUserService\x12I\n" +
	"\n" +
	"CreateUser\x12\x1c.tables.v1.CreateUserRequest\x1a\x1d.tables.v1.CreateUserResponse\x12d\n" +
	"\x13GetUserByExternalId\x12%.tables.v1.GetUserByExternalIdRequest\x1a&.tables.v1.GetUserByExternalIdResponse\x12C\n" +
	"\bGetUsers\x12\x1a.tables.v1.GetUsersRequest\x1a\x1b.tables.v1.GetUsersResponse2\xb0\x05\n" +
	"\vHostService\x12I\n" +
	"\n" +
	"CreateHost\x12\x1c.tables.v1.CreateHostRequest\x1a\x1d.tables.v1.CreateHostResponse\x12L\n" +
	"\vGetHostById\x12\x1d.tables.v1.GetHostByIdRequest\x1a\x1e.tables.v1.GetHostByIdResponse\x12C\n" +
	"\bGetHosts\x12\x1a.tables.v1.GetHostsRequest\x1a\x1b.tables.v1.GetHostsResponse\x12a\n" +
	"\x12GetHostsSearchName\x12$.tables.v1.GetHostsSearchNameRequest\x1a%.tables.v1.GetHostsSearchNameResponse\x12U\n" +
	"\x0eGetHostDeleted\x12 .tables.v1.GetHostDeletedRequest\x1a!.tables.v1.GetHostDeletedResponse\x12U\n" +
	"\x0eUpdateHostById\x12 .tables.v1.UpdateHostByIdRequest\x1a!.tables.v1.UpdateHostByIdResponse\x12U\n" +
	"\x0eDeleteHostById\x12 .tables.v1.DeleteHostByIdRequest\x1a!.tables.v1.DeleteHostByIdResponse\x12[\n" +
	"\x10UndeleteHostById\x12\".tables.v1.UndeleteHostByIdRequest\x1a#.tables.v1.UndeleteHostByIdResponseB^Z\\github.com/konstantin-suspitsyn/datacomrade/shared/pkg/proto/tables_model/tables/v1;tablesv1b\x06proto3"

var (
	file_tables_v1_tables_proto_rawDescOnce sync.Once
	file_tables_v1_tables_proto_rawDescData []byte
)

func file_tables_v1_tables_proto_rawDescGZIP() []byte {
	file_tables_v1_tables_proto_rawDescOnce.Do(func() {
		file_tables_v1_tables_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tables_v1_tables_proto_rawDesc), len(file_tables_v1_tables_proto_rawDesc)))
	})
	return file_tables_v1_tables_proto_rawDescData
}

var file_tables_v1_tables_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_tables_v1_tables_proto_goTypes = []any{
	(*Pagination)(nil),                  // 0: tables.v1.Pagination
	(*Alias)(nil),                       // 1: tables.v1.Alias
	(*CreateAliasRequest)(nil),          // 2: tables.v1.CreateAliasRequest
	(*CreateAliasResponse)(nil),         // 3: tables.v1.CreateAliasResponse
	(*GetAliasByIdRequest)(nil),         // 4: tables.v1.GetAliasByIdRequest
	(*GetAliasByIdResponse)(nil),        // 5: tables.v1.GetAliasByIdResponse
	(*GetAliasesDeletedRequest)(nil),    // 6: tables.v1.GetAliasesDeletedRequest
	(*GetAliasesDeletedResponse)(nil),   // 7: tables.v1.GetAliasesDeletedResponse
	(*GetAliasesRequest)(nil),           // 8: tables.v1.GetAliasesRequest
	(*GetAliasesResponse)(nil),          // 9: tables.v1.GetAliasesResponse
	(*UpdateAliasByIdRequest)(nil),      // 10: tables.v1.UpdateAliasByIdRequest
	(*UpdateAliasByIdResponse)(nil),     // 11: tables.v1.UpdateAliasByIdResponse
	(*DeleteAliasByIdRequest)(nil),      // 12: tables.v1.DeleteAliasByIdRequest
	(*DeleteAliasByIdResponse)(nil),     // 13: tables.v1.DeleteAliasByIdResponse
	(*UndeleteAliasByIdRequest)(nil),    // 14: tables.v1.UndeleteAliasByIdRequest
	(*UndeleteAliasByIdResponse)(nil),   // 15: tables.v1.UndeleteAliasByIdResponse
	(*User)(nil),                        // 16: tables.v1.User
	(*CreateUserRequest)(nil),           // 17: tables.v1.CreateUserRequest
	(*CreateUserResponse)(nil),          // 18: tables.v1.CreateUserResponse
	(*GetUserByExternalIdRequest)(nil),  // 19: tables.v1.GetUserByExternalIdRequest
	(*GetUserByExternalIdResponse)(nil), // 20: tables.v1.GetUserByExternalIdResponse
	(*GetUsersRequest)(nil),             // 21: tables.v1.GetUsersRequest
	(*GetUsersResponse)(nil),            // 22: tables.v1.GetUsersResponse
	(*Host)(nil),                        // 23: tables.v1.Host
	(*CreateHostRequest)(nil),           // 24: tables.v1.CreateHostRequest
	(*CreateHostResponse)(nil),          // 25: tables.v1.CreateHostResponse
	(*GetHostByIdRequest)(nil),          // 26: tables.v1.GetHostByIdRequest
	(*GetHostByIdResponse)(nil),         // 27: tables.v1.GetHostByIdResponse
	(*GetHostsRequest)(nil),             // 28: tables.v1.GetHostsRequest
	(*GetHostsResponse)(nil),            // 29: tables.v1.GetHostsResponse
	(*GetHostsSearchNameRequest)(nil),   // 30: tables.v1.GetHostsSearchNameRequest
	(*GetHostsSearchNameResponse)(nil),  // 31: tables.v1.GetHostsSearchNameResponse
	(*GetHostDeletedRequest)(nil),       // 32: tables.v1.GetHostDeletedRequest
	(*GetHostDeletedResponse)(nil),      // 33: tables.v1.GetHostDeletedResponse
	(*UpdateHostByIdRequest)(nil),       // 34: tables.v1.UpdateHostByIdRequest
	(*UpdateHostByIdResponse)(nil),      // 35: tables.v1.UpdateHostByIdResponse
	(*DeleteHostByIdRequest)(nil),       // 36: tables.v1.DeleteHostByIdRequest
	(*DeleteHostByIdResponse)(nil),      // 37: tables.v1.DeleteHostByIdResponse
	(*UndeleteHostByIdRequest)(nil),     // 38: tables.v1.UndeleteHostByIdRequest
	(*UndeleteHostByIdResponse)(nil),    // 39: tables.v1.UndeleteHostByIdResponse
	(*timestamppb.Timestamp)(nil),       // 40: google.protobuf.Timestamp
}
var file_tables_v1_tables_proto_depIdxs = []int32{
	40, // 0: tables.v1.Alias.created_at:type_name -> google.protobuf.Timestamp
	40, // 1: tables.v1.Alias.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 2: tables.v1.CreateAliasResponse.alias:type_name -> tables.v1.Alias
	1,  // 3: tables.v1.GetAliasByIdResponse.alias:type_name -> tables.v1.Alias
	1,  // 4: tables.v1.GetAliasesDeletedResponse.data:type_name -> tables.v1.Alias
	0,  // 5: tables.v1.GetAliasesDeletedResponse.pagination:type_name -> tables.v1.Pagination
	1,  // 6: tables.v1.GetAliasesResponse.data:type_name -> tables.v1.Alias
	0,  // 7: tables.v1.GetAliasesResponse.pagination:type_name -> tables.v1.Pagination
	40, // 8: tables.v1.User.created_at:type_name -> google.protobuf.Timestamp
	40, // 9: tables.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	16, // 10: tables.v1.CreateUserResponse.user:type_name -> tables.v1.User
	16, // 11: tables.v1.GetUserByExternalIdResponse.user:type_name -> tables.v1.User
	16, // 12: tables.v1.GetUsersResponse.data:type_name -> tables.v1.User
	0,  // 13: tables.v1.GetUsersResponse.pagination:type_name -> tables.v1.Pagination
	40, // 14: tables.v1.Host.created_at:type_name -> google.protobuf.Timestamp
	40, // 15: tables.v1.Host.updated_at:type_name -> google.protobuf.Timestamp
	23, // 16: tables.v1.CreateHostResponse.host:type_name -> tables.v1.Host
	23, // 17: tables.v1.GetHostByIdResponse.host:type_name -> tables.v1.Host
	23, // 18: tables.v1.GetHostsResponse.data:type_name -> tables.v1.Host
	0,  // 19: tables.v1.GetHostsResponse.pagination:type_name -> tables.v1.Pagination
	23, // 20: tables.v1.GetHostsSearchNameResponse.data:type_name -> tables.v1.Host
	0,  // 21: tables.v1.GetHostsSearchNameResponse.pagination:type_name -> tables.v1.Pagination
	23, // 22: tables.v1.GetHostDeletedResponse.data:type_name -> tables.v1.Host
	0,  // 23: tables.v1.GetHostDeletedResponse.pagination:type_name -> tables.v1.Pagination
	2,  // 24: tables.v1.AliasService.CreateAlias:input_type -> tables.v1.CreateAliasRequest
	4,  // 25: tables.v1.AliasService.GetAliasById:input_type -> tables.v1.GetAliasByIdRequest
	6,  // 26: tables.v1.AliasService.GetAliasesDeleted:input_type -> tables.v1.GetAliasesDeletedRequest
	8,  // 27: tables.v1.AliasService.GetAliases:input_type -> tables.v1.GetAliasesRequest
	10, // 28: tables.v1.AliasService.UpdateAliasById:input_type -> tables.v1.UpdateAliasByIdRequest
	12, // 29: tables.v1.AliasService.DeleteAliasById:input_type -> tables.v1.DeleteAliasByIdRequest
	14, // 30: tables.v1.AliasService.UndeleteAliasById:input_type -> tables.v1.UndeleteAliasByIdRequest
	17, // 31: tables.v1.UserService.CreateUser:input_type -> tables.v1.CreateUserRequest
	19, // 32: tables.v1.UserService.GetUserByExternalId:input_type -> tables.v1.GetUserByExternalIdRequest
	21, // 33: tables.v1.UserService.GetUsers:input_type -> tables.v1.GetUsersRequest
	24, // 34: tables.v1.HostService.CreateHost:input_type -> tables.v1.CreateHostRequest
	26, // 35: tables.v1.HostService.GetHostById:input_type -> tables.v1.GetHostByIdRequest
	28, // 36: tables.v1.HostService.GetHosts:input_type -> tables.v1.GetHostsRequest
	30, // 37: tables.v1.HostService.GetHostsSearchName:input_type -> tables.v1.GetHostsSearchNameRequest
	32, // 38: tables.v1.HostService.GetHostDeleted:input_type -> tables.v1.GetHostDeletedRequest
	34, // 39: tables.v1.HostService.UpdateHostById:input_type -> tables.v1.UpdateHostByIdRequest
	36, // 40: tables.v1.HostService.DeleteHostById:input_type -> tables.v1.DeleteHostByIdRequest
	38, // 41: tables.v1.HostService.UndeleteHostById:input_type -> tables.v1.UndeleteHostByIdRequest
	3,  // 42: tables.v1.AliasService.CreateAlias:output_type -> tables.v1.CreateAliasResponse
	5,  // 43: tables.v1.AliasService.GetAliasById:output_type -> tables.v1.GetAliasByIdResponse
	7,  // 44: tables.v1.AliasService.GetAliasesDeleted:output_type -> tables.v1.GetAliasesDeletedResponse
	9,  // 45: tables.v1.AliasService.GetAliases:output_type -> tables.v1.GetAliasesResponse
	11, // 46: tables.v1.AliasService.UpdateAliasById:output_type -> tables.v1.UpdateAliasByIdResponse
	13, // 47: tables.v1.AliasService.DeleteAliasById:output_type -> tables.v1.DeleteAliasByIdResponse
	15, // 48: tables.v1.AliasService.UndeleteAliasById:output_type -> tables.v1.UndeleteAliasByIdResponse
	18, // 49: tables.v1.UserService.CreateUser:output_type -> tables.v1.CreateUserResponse
	20, // 50: tables.v1.UserService.GetUserByExternalId:output_type -> tables.v1.GetUserByExternalIdResponse
	22, // 51: tables.v1.UserService.GetUsers:output_type -> tables.v1.GetUsersResponse
	25, // 52: tables.v1.HostService.CreateHost:output_type -> tables.v1.CreateHostResponse
	27, // 53: tables.v1.HostService.GetHostById:output_type -> tables.v1.GetHostByIdResponse
	29, // 54: tables.v1.HostService.GetHosts:output_type -> tables.v1.GetHostsResponse
	31, // 55: tables.v1.HostService.GetHostsSearchName:output_type -> tables.v1.GetHostsSearchNameResponse
	33, // 56: tables.v1.HostService.GetHostDeleted:output_type -> tables.v1.GetHostDeletedResponse
	35, // 57: tables.v1.HostService.UpdateHostById:output_type -> tables.v1.UpdateHostByIdResponse
	37, // 58: tables.v1.HostService.DeleteHostById:output_type -> tables.v1.DeleteHostByIdResponse
	39, // 59: tables.v1.HostService.UndeleteHostById:output_type -> tables.v1.UndeleteHostByIdResponse
	42, // [42:60] is the sub-list for method output_type
	24, // [24:42] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_tables_v1_tables_proto_init() }
func file_tables_v1_tables_proto_init() {
	if File_tables_v1_tables_proto != nil {
		return
	}
	file_tables_v1_tables_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tables_v1_tables_proto_rawDesc), len(file_tables_v1_tables_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_tables_v1_tables_proto_goTypes,
		DependencyIndexes: file_tables_v1_tables_proto_depIdxs,
		MessageInfos:      file_tables_v1_tables_proto_msgTypes,
	}.Build()
	File_tables_v1_tables_proto = out.File
	file_tables_v1_tables_proto_goTypes = nil
	file_tables_v1_tables_proto_depIdxs = nil
}
