// Файл сгенерирован программой SG Buddy https://github.com/konstantin-suspitsyn/sg_buddy
// Правки будут затёрты при следующей генерации: правьте настройки, а не этот файл.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: tables/v1/tables.proto

package tablesv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AliasService_CreateAlias_FullMethodName       = "/tables.v1.AliasService/CreateAlias"
	AliasService_GetAliasById_FullMethodName      = "/tables.v1.AliasService/GetAliasById"
	AliasService_GetAliasesDeleted_FullMethodName = "/tables.v1.AliasService/GetAliasesDeleted"
	AliasService_GetAliases_FullMethodName        = "/tables.v1.AliasService/GetAliases"
	AliasService_UpdateAliasById_FullMethodName   = "/tables.v1.AliasService/UpdateAliasById"
	AliasService_DeleteAliasById_FullMethodName   = "/tables.v1.AliasService/DeleteAliasById"
	AliasService_UndeleteAliasById_FullMethodName = "/tables.v1.AliasService/UndeleteAliasById"
)

// AliasServiceClient is the client API for AliasService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AliasServiceClient interface {
	CreateAlias(ctx context.Context, in *CreateAliasRequest, opts ...grpc.CallOption) (*CreateAliasResponse, error)
	GetAliasById(ctx context.Context, in *GetAliasByIdRequest, opts ...grpc.CallOption) (*GetAliasByIdResponse, error)
	GetAliasesDeleted(ctx context.Context, in *GetAliasesDeletedRequest, opts ...grpc.CallOption) (*GetAliasesDeletedResponse, error)
	GetAliases(ctx context.Context, in *GetAliasesRequest, opts ...grpc.CallOption) (*GetAliasesResponse, error)
	UpdateAliasById(ctx context.Context, in *UpdateAliasByIdRequest, opts ...grpc.CallOption) (*UpdateAliasByIdResponse, error)
	DeleteAliasById(ctx context.Context, in *DeleteAliasByIdRequest, opts ...grpc.CallOption) (*DeleteAliasByIdResponse, error)
	UndeleteAliasById(ctx context.Context, in *UndeleteAliasByIdRequest, opts ...grpc.CallOption) (*UndeleteAliasByIdResponse, error)
}

type aliasServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAliasServiceClient(cc grpc.ClientConnInterface) AliasServiceClient {
	return &aliasServiceClient{cc}
}

func (c *aliasServiceClient) CreateAlias(ctx context.Context, in *CreateAliasRequest, opts ...grpc.CallOption) (*CreateAliasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAliasResponse)
	err := c.cc.Invoke(ctx, AliasService_CreateAlias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aliasServiceClient) GetAliasById(ctx context.Context, in *GetAliasByIdRequest, opts ...grpc.CallOption) (*GetAliasByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAliasByIdResponse)
	err := c.cc.Invoke(ctx, AliasService_GetAliasById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aliasServiceClient) GetAliasesDeleted(ctx context.Context, in *GetAliasesDeletedRequest, opts ...grpc.CallOption) (*GetAliasesDeletedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAliasesDeletedResponse)
	err := c.cc.Invoke(ctx, AliasService_GetAliasesDeleted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aliasServiceClient) GetAliases(ctx context.Context, in *GetAliasesRequest, opts ...grpc.CallOption) (*GetAliasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAliasesResponse)
	err := c.cc.Invoke(ctx, AliasService_GetAliases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aliasServiceClient) UpdateAliasById(ctx context.Context, in *UpdateAliasByIdRequest, opts ...grpc.CallOption) (*UpdateAliasByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAliasByIdResponse)
	err := c.cc.Invoke(ctx, AliasService_UpdateAliasById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aliasServiceClient) DeleteAliasById(ctx context.Context, in *DeleteAliasByIdRequest, opts ...grpc.CallOption) (*DeleteAliasByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAliasByIdResponse)
	err := c.cc.Invoke(ctx, AliasService_DeleteAliasById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aliasServiceClient) UndeleteAliasById(ctx context.Context, in *UndeleteAliasByIdRequest, opts ...grpc.CallOption) (*UndeleteAliasByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UndeleteAliasByIdResponse)
	err := c.cc.Invoke(ctx, AliasService_UndeleteAliasById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AliasServiceServer is the server API for AliasService service.
// All implementations must embed UnimplementedAliasServiceServer
// for forward compatibility.
type AliasServiceServer interface {
	CreateAlias(context.Context, *CreateAliasRequest) (*CreateAliasResponse, error)
	GetAliasById(context.Context, *GetAliasByIdRequest) (*GetAliasByIdResponse, error)
	GetAliasesDeleted(context.Context, *GetAliasesDeletedRequest) (*GetAliasesDeletedResponse, error)
	GetAliases(context.Context, *GetAliasesRequest) (*GetAliasesResponse, error)
	UpdateAliasById(context.Context, *UpdateAliasByIdRequest) (*UpdateAliasByIdResponse, error)
	DeleteAliasById(context.Context, *DeleteAliasByIdRequest) (*DeleteAliasByIdResponse, error)
	UndeleteAliasById(context.Context, *UndeleteAliasByIdRequest) (*UndeleteAliasByIdResponse, error)
	mustEmbedUnimplementedAliasServiceServer()
}

// UnimplementedAliasServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAliasServiceServer struct{}

func (UnimplementedAliasServiceServer) CreateAlias(context.Context, *CreateAliasRequest) (*CreateAliasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAlias not implemented")
}
func (UnimplementedAliasServiceServer) GetAliasById(context.Context, *GetAliasByIdRequest) (*GetAliasByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAliasById not implemented")
}
func (UnimplementedAliasServiceServer) GetAliasesDeleted(context.Context, *GetAliasesDeletedRequest) (*GetAliasesDeletedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAliasesDeleted not implemented")
}
func (UnimplementedAliasServiceServer) GetAliases(context.Context, *GetAliasesRequest) (*GetAliasesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAliases not implemented")
}
func (UnimplementedAliasServiceServer) UpdateAliasById(context.Context, *UpdateAliasByIdRequest) (*UpdateAliasByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAliasById not implemented")
}
func (UnimplementedAliasServiceServer) DeleteAliasById(context.Context, *DeleteAliasByIdRequest) (*DeleteAliasByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAliasById not implemented")
}
func (UnimplementedAliasServiceServer) UndeleteAliasById(context.Context, *UndeleteAliasByIdRequest) (*UndeleteAliasByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UndeleteAliasById not implemented")
}
func (UnimplementedAliasServiceServer) mustEmbedUnimplementedAliasServiceServer() {}
func (UnimplementedAliasServiceServer) testEmbeddedByValue()                      {}

// UnsafeAliasServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AliasServiceServer will
// result in compilation errors.
type UnsafeAliasServiceServer interface {
	mustEmbedUnimplementedAliasServiceServer()
}

func RegisterAliasServiceServer(s grpc.ServiceRegistrar, srv AliasServiceServer) {
	// If the following call pancis, it indicates UnimplementedAliasServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AliasService_ServiceDesc, srv)
}

func _AliasService_CreateAlias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AliasServiceServer).CreateAlias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AliasService_CreateAlias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AliasServiceServer).CreateAlias(ctx, req.(*CreateAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AliasService_GetAliasById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAliasByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AliasServiceServer).GetAliasById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AliasService_GetAliasById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AliasServiceServer).GetAliasById(ctx, req.(*GetAliasByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AliasService_GetAliasesDeleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAliasesDeletedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AliasServiceServer).GetAliasesDeleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AliasService_GetAliasesDeleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AliasServiceServer).GetAliasesDeleted(ctx, req.(*GetAliasesDeletedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AliasService_GetAliases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAliasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AliasServiceServer).GetAliases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AliasService_GetAliases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AliasServiceServer).GetAliases(ctx, req.(*GetAliasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AliasService_UpdateAliasById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAliasByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AliasServiceServer).UpdateAliasById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AliasService_UpdateAliasById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AliasServiceServer).UpdateAliasById(ctx, req.(*UpdateAliasByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AliasService_DeleteAliasById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAliasByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AliasServiceServer).DeleteAliasById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AliasService_DeleteAliasById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AliasServiceServer).DeleteAliasById(ctx, req.(*DeleteAliasByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AliasService_UndeleteAliasById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UndeleteAliasByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AliasServiceServer).UndeleteAliasById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AliasService_UndeleteAliasById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AliasServiceServer).UndeleteAliasById(ctx, req.(*UndeleteAliasByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AliasService_ServiceDesc is the grpc.ServiceDesc for AliasService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AliasService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tables.v1.AliasService",
	HandlerType: (*AliasServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAlias",
			Handler:    _AliasService_CreateAlias_Handler,
		},
		{
			MethodName: "GetAliasById",
			Handler:    _AliasService_GetAliasById_Handler,
		},
		{
			MethodName: "GetAliasesDeleted",
			Handler:    _AliasService_GetAliasesDeleted_Handler,
		},
		{
			MethodName: "GetAliases",
			Handler:    _AliasService_GetAliases_Handler,
		},
		{
			MethodName: "UpdateAliasById",
			Handler:    _AliasService_UpdateAliasById_Handler,
		},
		{
			MethodName: "DeleteAliasById",
			Handler:    _AliasService_DeleteAliasById_Handler,
		},
		{
			MethodName: "UndeleteAliasById",
			Handler:    _AliasService_UndeleteAliasById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tables/v1/tables.proto",
}

const (
	UserService_CreateUser_FullMethodName          = "/tables.v1.UserService/CreateUser"
	UserService_GetUserByExternalId_FullMethodName = "/tables.v1.UserService/GetUserByExternalId"
	UserService_GetUsers_FullMethodName            = "/tables.v1.UserService/GetUsers"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	GetUserByExternalId(ctx context.Context, in *GetUserByExternalIdRequest, opts ...grpc.CallOption) (*GetUserByExternalIdResponse, error)
	GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, UserService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserByExternalId(ctx context.Context, in *GetUserByExternalIdRequest, opts ...grpc.CallOption) (*GetUserByExternalIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserByExternalIdResponse)
	err := c.cc.Invoke(ctx, UserService_GetUserByExternalId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUsersResponse)
	err := c.cc.Invoke(ctx, UserService_GetUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
type UserServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	GetUserByExternalId(context.Context, *GetUserByExternalIdRequest) (*GetUserByExternalIdResponse, error)
	GetUsers(context.Context, *GetUsersRequest) (*GetUsersResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedUserServiceServer) GetUserByExternalId(context.Context, *GetUserByExternalIdRequest) (*GetUserByExternalIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByExternalId not implemented")
}
func (UnimplementedUserServiceServer) GetUsers(context.Context, *GetUsersRequest) (*GetUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserByExternalId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByExternalIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserByExternalId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserByExternalId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserByExternalId(ctx, req.(*GetUserByExternalIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUsers(ctx, req.(*GetUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tables.v1.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "GetUserByExternalId",
			Handler:    _UserService_GetUserByExternalId_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _UserService_GetUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tables/v1/tables.proto",
}

const (
	HostService_CreateHost_FullMethodName         = "/tables.v1.HostService/CreateHost"
	HostService_GetHostById_FullMethodName        = "/tables.v1.HostService/GetHostById"
	HostService_GetHosts_FullMethodName           = "/tables.v1.HostService/GetHosts"
	HostService_GetHostsSearchName_FullMethodName = "/tables.v1.HostService/GetHostsSearchName"
	HostService_GetHostDeleted_FullMethodName     = "/tables.v1.HostService/GetHostDeleted"
	HostService_UpdateHostById_FullMethodName     = "/tables.v1.HostService/UpdateHostById"
	HostService_DeleteHostById_FullMethodName     = "/tables.v1.HostService/DeleteHostById"
	HostService_UndeleteHostById_FullMethodName   = "/tables.v1.HostService/UndeleteHostById"
)

// HostServiceClient is the client API for HostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HostServiceClient interface {
	CreateHost(ctx context.Context, in *CreateHostRequest, opts ...grpc.CallOption) (*CreateHostResponse, error)
	GetHostById(ctx context.Context, in *GetHostByIdRequest, opts ...grpc.CallOption) (*GetHostByIdResponse, error)
	GetHosts(ctx context.Context, in *GetHostsRequest, opts ...grpc.CallOption) (*GetHostsResponse, error)
	GetHostsSearchName(ctx context.Context, in *GetHostsSearchNameRequest, opts ...grpc.CallOption) (*GetHostsSearchNameResponse, error)
	GetHostDeleted(ctx context.Context, in *GetHostDeletedRequest, opts ...grpc.CallOption) (*GetHostDeletedResponse, error)
	UpdateHostById(ctx context.Context, in *UpdateHostByIdRequest, opts ...grpc.CallOption) (*UpdateHostByIdResponse, error)
	DeleteHostById(ctx context.Context, in *DeleteHostByIdRequest, opts ...grpc.CallOption) (*DeleteHostByIdResponse, error)
	UndeleteHostById(ctx context.Context, in *UndeleteHostByIdRequest, opts ...grpc.CallOption) (*UndeleteHostByIdResponse, error)
}

type hostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHostServiceClient(cc grpc.ClientConnInterface) HostServiceClient {
	return &hostServiceClient{cc}
}

func (c *hostServiceClient) CreateHost(ctx context.Context, in *CreateHostRequest, opts ...grpc.CallOption) (*CreateHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateHostResponse)
	err := c.cc.Invoke(ctx, HostService_CreateHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) GetHostById(ctx context.Context, in *GetHostByIdRequest, opts ...grpc.CallOption) (*GetHostByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHostByIdResponse)
	err := c.cc.Invoke(ctx, HostService_GetHostById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) GetHosts(ctx context.Context, in *GetHostsRequest, opts ...grpc.CallOption) (*GetHostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHostsResponse)
	err := c.cc.Invoke(ctx, HostService_GetHosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) GetHostsSearchName(ctx context.Context, in *GetHostsSearchNameRequest, opts ...grpc.CallOption) (*GetHostsSearchNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHostsSearchNameResponse)
	err := c.cc.Invoke(ctx, HostService_GetHostsSearchName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) GetHostDeleted(ctx context.Context, in *GetHostDeletedRequest, opts ...grpc.CallOption) (*GetHostDeletedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHostDeletedResponse)
	err := c.cc.Invoke(ctx, HostService_GetHostDeleted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) UpdateHostById(ctx context.Context, in *UpdateHostByIdRequest, opts ...grpc.CallOption) (*UpdateHostByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateHostByIdResponse)
	err := c.cc.Invoke(ctx, HostService_UpdateHostById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) DeleteHostById(ctx context.Context, in *DeleteHostByIdRequest, opts ...grpc.CallOption) (*DeleteHostByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteHostByIdResponse)
	err := c.cc.Invoke(ctx, HostService_DeleteHostById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) UndeleteHostById(ctx context.Context, in *UndeleteHostByIdRequest, opts ...grpc.CallOption) (*UndeleteHostByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UndeleteHostByIdResponse)
	err := c.cc.Invoke(ctx, HostService_UndeleteHostById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostServiceServer is the server API for HostService service.
// All implementations must embed UnimplementedHostServiceServer
// for forward compatibility.
type HostServiceServer interface {
	CreateHost(context.Context, *CreateHostRequest) (*CreateHostResponse, error)
	GetHostById(context.Context, *GetHostByIdRequest) (*GetHostByIdResponse, error)
	GetHosts(context.Context, *GetHostsRequest) (*GetHostsResponse, error)
	GetHostsSearchName(context.Context, *GetHostsSearchNameRequest) (*GetHostsSearchNameResponse, error)
	GetHostDeleted(context.Context, *GetHostDeletedRequest) (*GetHostDeletedResponse, error)
	UpdateHostById(context.Context, *UpdateHostByIdRequest) (*UpdateHostByIdResponse, error)
	DeleteHostById(context.Context, *DeleteHostByIdRequest) (*DeleteHostByIdResponse, error)
	UndeleteHostById(context.Context, *UndeleteHostByIdRequest) (*UndeleteHostByIdResponse, error)
	mustEmbedUnimplementedHostServiceServer()
}

// UnimplementedHostServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostServiceServer struct{}

func (UnimplementedHostServiceServer) CreateHost(context.Context, *CreateHostRequest) (*CreateHostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHost not implemented")
}
func (UnimplementedHostServiceServer) GetHostById(context.Context, *GetHostByIdRequest) (*GetHostByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHostById not implemented")
}
func (UnimplementedHostServiceServer) GetHosts(context.Context, *GetHostsRequest) (*GetHostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHosts not implemented")
}
func (UnimplementedHostServiceServer) GetHostsSearchName(context.Context, *GetHostsSearchNameRequest) (*GetHostsSearchNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHostsSearchName not implemented")
}
func (UnimplementedHostServiceServer) GetHostDeleted(context.Context, *GetHostDeletedRequest) (*GetHostDeletedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHostDeleted not implemented")
}
func (UnimplementedHostServiceServer) UpdateHostById(context.Context, *UpdateHostByIdRequest) (*UpdateHostByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHostById not implemented")
}
func (UnimplementedHostServiceServer) DeleteHostById(context.Context, *DeleteHostByIdRequest) (*DeleteHostByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHostById not implemented")
}
func (UnimplementedHostServiceServer) UndeleteHostById(context.Context, *UndeleteHostByIdRequest) (*UndeleteHostByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UndeleteHostById not implemented")
}
func (UnimplementedHostServiceServer) mustEmbedUnimplementedHostServiceServer() {}
func (UnimplementedHostServiceServer) testEmbeddedByValue()                     {}

// UnsafeHostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostServiceServer will
// result in compilation errors.
type UnsafeHostServiceServer interface {
	mustEmbedUnimplementedHostServiceServer()
}

func RegisterHostServiceServer(s grpc.ServiceRegistrar, srv HostServiceServer) {
	// If the following call pancis, it indicates UnimplementedHostServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostService_ServiceDesc, srv)
}

func _HostService_CreateHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).CreateHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_CreateHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).CreateHost(ctx, req.(*CreateHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_GetHostById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).GetHostById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_GetHostById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).GetHostById(ctx, req.(*GetHostByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_GetHosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).GetHosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_GetHosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).GetHosts(ctx, req.(*GetHostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_GetHostsSearchName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostsSearchNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).GetHostsSearchName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_GetHostsSearchName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).GetHostsSearchName(ctx, req.(*GetHostsSearchNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_GetHostDeleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostDeletedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).GetHostDeleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_GetHostDeleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).GetHostDeleted(ctx, req.(*GetHostDeletedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_UpdateHostById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHostByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).UpdateHostById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_UpdateHostById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).UpdateHostById(ctx, req.(*UpdateHostByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_DeleteHostById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHostByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).DeleteHostById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_DeleteHostById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).DeleteHostById(ctx, req.(*DeleteHostByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_UndeleteHostById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UndeleteHostByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).UndeleteHostById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_UndeleteHostById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).UndeleteHostById(ctx, req.(*UndeleteHostByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostService_ServiceDesc is the grpc.ServiceDesc for HostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tables.v1.HostService",
	HandlerType: (*HostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateHost",
			Handler:    _HostService_CreateHost_Handler,
		},
		{
			MethodName: "GetHostById",
			Handler:    _HostService_GetHostById_Handler,
		},
		{
			MethodName: "GetHosts",
			Handler:    _HostService_GetHosts_Handler,
		},
		{
			MethodName: "GetHostsSearchName",
			Handler:    _HostService_GetHostsSearchName_Handler,
		},
		{
			MethodName: "GetHostDeleted",
			Handler:    _HostService_GetHostDeleted_Handler,
		},
		{
			MethodName: "UpdateHostById",
			Handler:    _HostService_UpdateHostById_Handler,
		},
		{
			MethodName: "DeleteHostById",
			Handler:    _HostService_DeleteHostById_Handler,
		},
		{
			MethodName: "UndeleteHostById",
			Handler:    _HostService_UndeleteHostById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tables/v1/tables.proto",
}
