// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sharedmodels

import (
	"database/sql"
	"time"
)

type SharedDomain struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IsDeleted   bool           `json:"is_deleted"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	UserID      int64          `json:"user_id"`
}
