// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sharedmodels

import (
	"database/sql"
	"time"
)

type SharedDomain struct {
	ID          int64
	Name        string
	Description sql.NullString
	IsDeleted   bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserID      int64
}
