// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sharedmodels

import (
	"context"
	"database/sql"
	"time"
)

const countActiveRows = `-- name: CountActiveRows :one
SELECT count(*) from shared."domain"
where is_deleted = false
`

func (q *Queries) CountActiveRows(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveRows)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDomain = `-- name: CreateDomain :one
INSERT INTO shared."domain"
("name", description, user_id, is_deleted, created_at, updated_at)
VALUES($1, $2, $3, false, now(), now())
RETURNING id, name, description, is_deleted, created_at, updated_at, user_id
`

type CreateDomainParams struct {
	Name        string
	Description sql.NullString
	UserID      int64
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (SharedDomain, error) {
	row := q.db.QueryRowContext(ctx, createDomain, arg.Name, arg.Description, arg.UserID)
	var i SharedDomain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteDomain = `-- name: DeleteDomain :exec
UPDATE shared."domain"
	SET is_deleted = true,
	updated_at = now()
WHERE id = $1
`

func (q *Queries) DeleteDomain(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDomain, id)
	return err
}

const getDomainById = `-- name: GetDomainById :one
SELECT id, "name", description, user_id, created_at, updated_at
FROM shared."domain"
where is_deleted = false
AND id = $1
`

type GetDomainByIdRow struct {
	ID          int64
	Name        string
	Description sql.NullString
	UserID      int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetDomainById(ctx context.Context, id int64) (GetDomainByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getDomainById, id)
	var i GetDomainByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDomains = `-- name: GetDomains :many
SELECT id, "name", description, user_id, created_at, updated_at
FROM shared."domain"
where is_deleted = false
ORDER BY id
`

type GetDomainsRow struct {
	ID          int64
	Name        string
	Description sql.NullString
	UserID      int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetDomains(ctx context.Context) ([]GetDomainsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDomainsRow
	for rows.Next() {
		var i GetDomainsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
