// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package auth_logic

import (
	"time"

	"github.com/google/uuid"
)

type DcDomainRole struct {
	ID          int64
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	IsDeleted   bool
}

type DcTableCat struct {
	ID          int64
	Name        string
	Description string
	SchemaID    int64
	TableTypeID int64
	DomainID    int64
	IsDeleted   bool
	IsGetDict   bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserID      int64
}

type DcTableRole struct {
	ID          int64
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	IsDeleted   bool
}

type DcUser struct {
	ID         int64
	Name       string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	IsDeleted  bool
	ExternalID uuid.UUID
}

type DcUserDomainRole struct {
	ID            int64
	UserID        int64
	DomainRolesID int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	IsDeleted     bool
	DomainID      int64
}

type DcUserTableRole struct {
	ID           int64
	UserID       int64
	TableRolesID int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
	IsDeleted    bool
	TableID      int64
}
