// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package auth_logic

import (
	"context"

	"github.com/google/uuid"
)

const getTableIdsByExternalUserIdAndRoles = `-- name: GetTableIdsByExternalUserIdAndRoles :many


with filtered_user as (select id
                       from dc."user"
                       where external_id = $1),
     all_domains as (
         -- Все домены, которые пользователь может прочитать
         select udr.domain_id
         from dc.user_domain_roles udr
                  inner join dc.domain_roles dr on dr.id = udr.domain_roles_id
         where udr.user_id = (select id from filtered_user)
           and dr.name in ($2))
        ,
     all_tables_with_role_and_user as (
         -- Все таблицы, которые пользователь может прочитать
         select utr.table_id
         from dc.user_table_roles utr
                  join dc.table_roles tr on tr.id = utr.table_roles_id
         where tr.name in ($2)
           and utr.user_id = (select id from filtered_user))

select tc.id
from dc.table_cat tc
where tc.domain_id in (select domain_id from all_domains)
   or tc.id in (select table_id from all_tables_with_role_and_user)
`

type GetTableIdsByExternalUserIdAndRolesParams struct {
	ExternalID uuid.UUID
	Name       string
}

// =========================================================
// Логика авторизации. А именно доступные поля и таблицы
// =========================================================
// =========================================================
// Таблицы, доступные пользователю
// =========================================================
func (q *Queries) GetTableIdsByExternalUserIdAndRoles(ctx context.Context, arg GetTableIdsByExternalUserIdAndRolesParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getTableIdsByExternalUserIdAndRoles, arg.ExternalID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTableIdsByUserIdAndRoles = `-- name: GetTableIdsByUserIdAndRoles :many
with all_domains as (
         -- Все домены, которые пользователь может прочитать
         select udr.domain_id
         from dc.user_domain_roles udr
                  inner join dc.domain_roles dr on dr.id = udr.domain_roles_id
         where udr.user_id = $1
           and dr.name in ($2))
        ,
     all_tables_with_role_and_user as (
         -- Все таблицы, которые пользователь может прочитать
         select utr.table_id
         from dc.user_table_roles utr
                  join dc.table_roles tr on tr.id = utr.table_roles_id
         where tr.name in ($2)
           and utr.user_id = $1)

select tc.id
from dc.table_cat tc
where tc.domain_id in (select domain_id from all_domains)
   or tc.id in (select table_id from all_tables_with_role_and_user)
`

type GetTableIdsByUserIdAndRolesParams struct {
	UserID int64
	Name   string
}

func (q *Queries) GetTableIdsByUserIdAndRoles(ctx context.Context, arg GetTableIdsByUserIdAndRolesParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getTableIdsByUserIdAndRoles, arg.UserID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
